//
// Licensed to the Apache Software Foundation (ASF) under one or more
// license agreements; and to You under the Apache License, version 2.0:
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// This file is part of the Apache Pekko project, which was derived from Akka.

//
// Copyright (C) 2009-2022 Lightbend Inc. <https://www.lightbend.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ClusterMessages.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Reachability status
type ReachabilityStatus int32

const (
	ReachabilityStatus_Reachable   ReachabilityStatus = 0
	ReachabilityStatus_Unreachable ReachabilityStatus = 1
	ReachabilityStatus_Terminated  ReachabilityStatus = 2
)

// Enum value maps for ReachabilityStatus.
var (
	ReachabilityStatus_name = map[int32]string{
		0: "Reachable",
		1: "Unreachable",
		2: "Terminated",
	}
	ReachabilityStatus_value = map[string]int32{
		"Reachable":   0,
		"Unreachable": 1,
		"Terminated":  2,
	}
)

func (x ReachabilityStatus) Enum() *ReachabilityStatus {
	p := new(ReachabilityStatus)
	*p = x
	return p
}

func (x ReachabilityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReachabilityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ClusterMessages_proto_enumTypes[0].Descriptor()
}

func (ReachabilityStatus) Type() protoreflect.EnumType {
	return &file_ClusterMessages_proto_enumTypes[0]
}

func (x ReachabilityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ReachabilityStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ReachabilityStatus(num)
	return nil
}

// Deprecated: Use ReachabilityStatus.Descriptor instead.
func (ReachabilityStatus) EnumDescriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{0}
}

// *
// Member Status
type MemberStatus int32

const (
	MemberStatus_Joining              MemberStatus = 0
	MemberStatus_Up                   MemberStatus = 1
	MemberStatus_Leaving              MemberStatus = 2
	MemberStatus_Exiting              MemberStatus = 3
	MemberStatus_Down                 MemberStatus = 4
	MemberStatus_Removed              MemberStatus = 5
	MemberStatus_WeaklyUp             MemberStatus = 6
	MemberStatus_PreparingForShutdown MemberStatus = 7
	MemberStatus_ReadyForShutdown     MemberStatus = 8
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "Joining",
		1: "Up",
		2: "Leaving",
		3: "Exiting",
		4: "Down",
		5: "Removed",
		6: "WeaklyUp",
		7: "PreparingForShutdown",
		8: "ReadyForShutdown",
	}
	MemberStatus_value = map[string]int32{
		"Joining":              0,
		"Up":                   1,
		"Leaving":              2,
		"Exiting":              3,
		"Down":                 4,
		"Removed":              5,
		"WeaklyUp":             6,
		"PreparingForShutdown": 7,
		"ReadyForShutdown":     8,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ClusterMessages_proto_enumTypes[1].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_ClusterMessages_proto_enumTypes[1]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MemberStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MemberStatus(num)
	return nil
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{1}
}

type ConfigCheck_Type int32

const (
	ConfigCheck_UncheckedConfig    ConfigCheck_Type = 1
	ConfigCheck_IncompatibleConfig ConfigCheck_Type = 2
	ConfigCheck_CompatibleConfig   ConfigCheck_Type = 3
)

// Enum value maps for ConfigCheck_Type.
var (
	ConfigCheck_Type_name = map[int32]string{
		1: "UncheckedConfig",
		2: "IncompatibleConfig",
		3: "CompatibleConfig",
	}
	ConfigCheck_Type_value = map[string]int32{
		"UncheckedConfig":    1,
		"IncompatibleConfig": 2,
		"CompatibleConfig":   3,
	}
)

func (x ConfigCheck_Type) Enum() *ConfigCheck_Type {
	p := new(ConfigCheck_Type)
	*p = x
	return p
}

func (x ConfigCheck_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigCheck_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_ClusterMessages_proto_enumTypes[2].Descriptor()
}

func (ConfigCheck_Type) Type() protoreflect.EnumType {
	return &file_ClusterMessages_proto_enumTypes[2]
}

func (x ConfigCheck_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ConfigCheck_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ConfigCheck_Type(num)
	return nil
}

// Deprecated: Use ConfigCheck_Type.Descriptor instead.
func (ConfigCheck_Type) EnumDescriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{4, 0}
}

// *
// Join
type Join struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *UniqueAddress         `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	AppVersion    *string                `protobuf:"bytes,3,opt,name=appVersion" json:"appVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_ClusterMessages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{0}
}

func (x *Join) GetNode() *UniqueAddress {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Join) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Join) GetAppVersion() string {
	if x != nil && x.AppVersion != nil {
		return *x.AppVersion
	}
	return ""
}

// *
// Welcome, reply to Join
type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *UniqueAddress         `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	Gossip        *Gossip                `protobuf:"bytes,2,req,name=gossip" json:"gossip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_ClusterMessages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{1}
}

func (x *Welcome) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Welcome) GetGossip() *Gossip {
	if x != nil {
		return x.Gossip
	}
	return nil
}

// *
// InitJoin
type InitJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentConfig *string                `protobuf:"bytes,1,opt,name=currentConfig" json:"currentConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitJoin) Reset() {
	*x = InitJoin{}
	mi := &file_ClusterMessages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitJoin) ProtoMessage() {}

func (x *InitJoin) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitJoin.ProtoReflect.Descriptor instead.
func (*InitJoin) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{2}
}

func (x *InitJoin) GetCurrentConfig() string {
	if x != nil && x.CurrentConfig != nil {
		return *x.CurrentConfig
	}
	return ""
}

// *
// InitJoinAck
type InitJoinAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	ConfigCheck   *ConfigCheck           `protobuf:"bytes,2,req,name=configCheck" json:"configCheck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitJoinAck) Reset() {
	*x = InitJoinAck{}
	mi := &file_ClusterMessages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitJoinAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitJoinAck) ProtoMessage() {}

func (x *InitJoinAck) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitJoinAck.ProtoReflect.Descriptor instead.
func (*InitJoinAck) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{3}
}

func (x *InitJoinAck) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *InitJoinAck) GetConfigCheck() *ConfigCheck {
	if x != nil {
		return x.ConfigCheck
	}
	return nil
}

type ConfigCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *ConfigCheck_Type      `protobuf:"varint,1,req,name=type,enum=pekko.cluster.ConfigCheck_Type" json:"type,omitempty"`
	ClusterConfig *string                `protobuf:"bytes,2,opt,name=clusterConfig" json:"clusterConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigCheck) Reset() {
	*x = ConfigCheck{}
	mi := &file_ClusterMessages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigCheck) ProtoMessage() {}

func (x *ConfigCheck) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigCheck.ProtoReflect.Descriptor instead.
func (*ConfigCheck) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigCheck) GetType() ConfigCheck_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ConfigCheck_UncheckedConfig
}

func (x *ConfigCheck) GetClusterConfig() string {
	if x != nil && x.ClusterConfig != nil {
		return *x.ClusterConfig
	}
	return ""
}

// *
// Prior to version 2.5.24
// Heartbeat sends an Address
// Version 2.5.24 can deserialize this message but does not send it.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Address               `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	SequenceNr    *int64                 `protobuf:"varint,2,opt,name=sequenceNr" json:"sequenceNr,omitempty"`
	CreationTime  *int64                 `protobuf:"zigzag64,3,opt,name=creationTime" json:"creationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_ClusterMessages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetFrom() *Address {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Heartbeat) GetSequenceNr() int64 {
	if x != nil && x.SequenceNr != nil {
		return *x.SequenceNr
	}
	return 0
}

func (x *Heartbeat) GetCreationTime() int64 {
	if x != nil && x.CreationTime != nil {
		return *x.CreationTime
	}
	return 0
}

// *
// Prior to version 2.5.24
// HeartbeatRsp Sends an UniqueAddress
// Version 2.5.24 can deserialize this message but does not send it.
type HeartBeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *UniqueAddress         `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	SequenceNr    *int64                 `protobuf:"varint,2,opt,name=sequenceNr" json:"sequenceNr,omitempty"`
	CreationTime  *int64                 `protobuf:"varint,3,opt,name=creationTime" json:"creationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	mi := &file_ClusterMessages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{6}
}

func (x *HeartBeatResponse) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *HeartBeatResponse) GetSequenceNr() int64 {
	if x != nil && x.SequenceNr != nil {
		return *x.SequenceNr
	}
	return 0
}

func (x *HeartBeatResponse) GetCreationTime() int64 {
	if x != nil && x.CreationTime != nil {
		return *x.CreationTime
	}
	return 0
}

// *
// Gossip Envelope
type GossipEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	From             *UniqueAddress         `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	To               *UniqueAddress         `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
	SerializedGossip []byte                 `protobuf:"bytes,3,req,name=serializedGossip" json:"serializedGossip,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GossipEnvelope) Reset() {
	*x = GossipEnvelope{}
	mi := &file_ClusterMessages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEnvelope) ProtoMessage() {}

func (x *GossipEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEnvelope.ProtoReflect.Descriptor instead.
func (*GossipEnvelope) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{7}
}

func (x *GossipEnvelope) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GossipEnvelope) GetTo() *UniqueAddress {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GossipEnvelope) GetSerializedGossip() []byte {
	if x != nil {
		return x.SerializedGossip
	}
	return nil
}

// *
// Gossip Status
type GossipStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *UniqueAddress         `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	AllHashes     []string               `protobuf:"bytes,2,rep,name=allHashes" json:"allHashes,omitempty"`
	Version       *VectorClock           `protobuf:"bytes,3,req,name=version" json:"version,omitempty"`
	SeenDigest    []byte                 `protobuf:"bytes,4,opt,name=seenDigest" json:"seenDigest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipStatus) Reset() {
	*x = GossipStatus{}
	mi := &file_ClusterMessages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipStatus) ProtoMessage() {}

func (x *GossipStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipStatus.ProtoReflect.Descriptor instead.
func (*GossipStatus) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{8}
}

func (x *GossipStatus) GetFrom() *UniqueAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GossipStatus) GetAllHashes() []string {
	if x != nil {
		return x.AllHashes
	}
	return nil
}

func (x *GossipStatus) GetVersion() *VectorClock {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GossipStatus) GetSeenDigest() []byte {
	if x != nil {
		return x.SeenDigest
	}
	return nil
}

// *
// Gossip
type Gossip struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AllAddresses   []*UniqueAddress       `protobuf:"bytes,1,rep,name=allAddresses" json:"allAddresses,omitempty"`
	AllRoles       []string               `protobuf:"bytes,2,rep,name=allRoles" json:"allRoles,omitempty"`
	AllHashes      []string               `protobuf:"bytes,3,rep,name=allHashes" json:"allHashes,omitempty"`
	Members        []*Member              `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	Overview       *GossipOverview        `protobuf:"bytes,5,req,name=overview" json:"overview,omitempty"`
	Version        *VectorClock           `protobuf:"bytes,6,req,name=version" json:"version,omitempty"`
	Tombstones     []*Tombstone           `protobuf:"bytes,7,rep,name=tombstones" json:"tombstones,omitempty"`
	AllAppVersions []string               `protobuf:"bytes,8,rep,name=allAppVersions" json:"allAppVersions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Gossip) Reset() {
	*x = Gossip{}
	mi := &file_ClusterMessages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gossip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gossip) ProtoMessage() {}

func (x *Gossip) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gossip.ProtoReflect.Descriptor instead.
func (*Gossip) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{9}
}

func (x *Gossip) GetAllAddresses() []*UniqueAddress {
	if x != nil {
		return x.AllAddresses
	}
	return nil
}

func (x *Gossip) GetAllRoles() []string {
	if x != nil {
		return x.AllRoles
	}
	return nil
}

func (x *Gossip) GetAllHashes() []string {
	if x != nil {
		return x.AllHashes
	}
	return nil
}

func (x *Gossip) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Gossip) GetOverview() *GossipOverview {
	if x != nil {
		return x.Overview
	}
	return nil
}

func (x *Gossip) GetVersion() *VectorClock {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Gossip) GetTombstones() []*Tombstone {
	if x != nil {
		return x.Tombstones
	}
	return nil
}

func (x *Gossip) GetAllAppVersions() []string {
	if x != nil {
		return x.AllAppVersions
	}
	return nil
}

// *
// Gossip Overview
type GossipOverview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the address indexes for the nodes that have seen this gossip
	Seen                 []int32                 `protobuf:"varint,1,rep,name=seen" json:"seen,omitempty"`
	ObserverReachability []*ObserverReachability `protobuf:"bytes,2,rep,name=observerReachability" json:"observerReachability,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GossipOverview) Reset() {
	*x = GossipOverview{}
	mi := &file_ClusterMessages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipOverview) ProtoMessage() {}

func (x *GossipOverview) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipOverview.ProtoReflect.Descriptor instead.
func (*GossipOverview) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{10}
}

func (x *GossipOverview) GetSeen() []int32 {
	if x != nil {
		return x.Seen
	}
	return nil
}

func (x *GossipOverview) GetObserverReachability() []*ObserverReachability {
	if x != nil {
		return x.ObserverReachability
	}
	return nil
}

// *
// Reachability
type ObserverReachability struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AddressIndex        *int32                 `protobuf:"varint,1,req,name=addressIndex" json:"addressIndex,omitempty"`
	Version             *int64                 `protobuf:"varint,4,req,name=version" json:"version,omitempty"`
	SubjectReachability []*SubjectReachability `protobuf:"bytes,2,rep,name=subjectReachability" json:"subjectReachability,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ObserverReachability) Reset() {
	*x = ObserverReachability{}
	mi := &file_ClusterMessages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverReachability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverReachability) ProtoMessage() {}

func (x *ObserverReachability) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverReachability.ProtoReflect.Descriptor instead.
func (*ObserverReachability) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{11}
}

func (x *ObserverReachability) GetAddressIndex() int32 {
	if x != nil && x.AddressIndex != nil {
		return *x.AddressIndex
	}
	return 0
}

func (x *ObserverReachability) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *ObserverReachability) GetSubjectReachability() []*SubjectReachability {
	if x != nil {
		return x.SubjectReachability
	}
	return nil
}

type SubjectReachability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressIndex  *int32                 `protobuf:"varint,1,req,name=addressIndex" json:"addressIndex,omitempty"`
	Status        *ReachabilityStatus    `protobuf:"varint,3,req,name=status,enum=pekko.cluster.ReachabilityStatus" json:"status,omitempty"`
	Version       *int64                 `protobuf:"varint,4,req,name=version" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectReachability) Reset() {
	*x = SubjectReachability{}
	mi := &file_ClusterMessages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectReachability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectReachability) ProtoMessage() {}

func (x *SubjectReachability) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectReachability.ProtoReflect.Descriptor instead.
func (*SubjectReachability) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{12}
}

func (x *SubjectReachability) GetAddressIndex() int32 {
	if x != nil && x.AddressIndex != nil {
		return *x.AddressIndex
	}
	return 0
}

func (x *SubjectReachability) GetStatus() ReachabilityStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ReachabilityStatus_Reachable
}

func (x *SubjectReachability) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type Tombstone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressIndex  *int32                 `protobuf:"varint,1,req,name=addressIndex" json:"addressIndex,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tombstone) Reset() {
	*x = Tombstone{}
	mi := &file_ClusterMessages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tombstone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tombstone) ProtoMessage() {}

func (x *Tombstone) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tombstone.ProtoReflect.Descriptor instead.
func (*Tombstone) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{13}
}

func (x *Tombstone) GetAddressIndex() int32 {
	if x != nil && x.AddressIndex != nil {
		return *x.AddressIndex
	}
	return 0
}

func (x *Tombstone) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

// *
// Member
type Member struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AddressIndex    *int32                 `protobuf:"varint,1,req,name=addressIndex" json:"addressIndex,omitempty"`
	UpNumber        *int32                 `protobuf:"varint,2,req,name=upNumber" json:"upNumber,omitempty"`
	Status          *MemberStatus          `protobuf:"varint,3,req,name=status,enum=pekko.cluster.MemberStatus" json:"status,omitempty"`
	RolesIndexes    []int32                `protobuf:"varint,4,rep,packed,name=rolesIndexes" json:"rolesIndexes,omitempty"`
	AppVersionIndex *int32                 `protobuf:"varint,5,opt,name=appVersionIndex" json:"appVersionIndex,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_ClusterMessages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{14}
}

func (x *Member) GetAddressIndex() int32 {
	if x != nil && x.AddressIndex != nil {
		return *x.AddressIndex
	}
	return 0
}

func (x *Member) GetUpNumber() int32 {
	if x != nil && x.UpNumber != nil {
		return *x.UpNumber
	}
	return 0
}

func (x *Member) GetStatus() MemberStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return MemberStatus_Joining
}

func (x *Member) GetRolesIndexes() []int32 {
	if x != nil {
		return x.RolesIndexes
	}
	return nil
}

func (x *Member) GetAppVersionIndex() int32 {
	if x != nil && x.AppVersionIndex != nil {
		return *x.AppVersionIndex
	}
	return 0
}

// *
// Vector Clock
type VectorClock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the timestamp could be removed but left for test data compatibility
	Timestamp     *int64                 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Versions      []*VectorClock_Version `protobuf:"bytes,2,rep,name=versions" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_ClusterMessages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{15}
}

func (x *VectorClock) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *VectorClock) GetVersions() []*VectorClock_Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

// *
// An empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ClusterMessages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{16}
}

// *
// Defines a remote address.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *string                `protobuf:"bytes,1,req,name=system" json:"system,omitempty"`
	Hostname      *string                `protobuf:"bytes,2,req,name=hostname" json:"hostname,omitempty"`
	Port          *uint32                `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	Protocol      *string                `protobuf:"bytes,4,opt,name=protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_ClusterMessages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{17}
}

func (x *Address) GetSystem() string {
	if x != nil && x.System != nil {
		return *x.System
	}
	return ""
}

func (x *Address) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *Address) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *Address) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

// *
// Defines a remote address with uid.
type UniqueAddress struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address *Address               `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Uid     *uint32                `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	// 64 bit uids but with backward wire compatibility
	Uid2          *uint32 `protobuf:"varint,3,opt,name=uid2" json:"uid2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueAddress) Reset() {
	*x = UniqueAddress{}
	mi := &file_ClusterMessages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueAddress) ProtoMessage() {}

func (x *UniqueAddress) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueAddress.ProtoReflect.Descriptor instead.
func (*UniqueAddress) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{18}
}

func (x *UniqueAddress) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UniqueAddress) GetUid() uint32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *UniqueAddress) GetUid2() uint32 {
	if x != nil && x.Uid2 != nil {
		return *x.Uid2
	}
	return 0
}

type ClusterRouterPool struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Pool          *Pool                      `protobuf:"bytes,1,req,name=pool" json:"pool,omitempty"`
	Settings      *ClusterRouterPoolSettings `protobuf:"bytes,2,req,name=settings" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRouterPool) Reset() {
	*x = ClusterRouterPool{}
	mi := &file_ClusterMessages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRouterPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRouterPool) ProtoMessage() {}

func (x *ClusterRouterPool) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRouterPool.ProtoReflect.Descriptor instead.
func (*ClusterRouterPool) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{19}
}

func (x *ClusterRouterPool) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *ClusterRouterPool) GetSettings() *ClusterRouterPoolSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Pool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerializerId  *uint32                `protobuf:"varint,1,req,name=serializerId" json:"serializerId,omitempty"`
	Manifest      *string                `protobuf:"bytes,2,req,name=manifest" json:"manifest,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_ClusterMessages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{20}
}

func (x *Pool) GetSerializerId() uint32 {
	if x != nil && x.SerializerId != nil {
		return *x.SerializerId
	}
	return 0
}

func (x *Pool) GetManifest() string {
	if x != nil && x.Manifest != nil {
		return *x.Manifest
	}
	return ""
}

func (x *Pool) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClusterRouterPoolSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalInstances      *uint32                `protobuf:"varint,1,req,name=totalInstances" json:"totalInstances,omitempty"`
	MaxInstancesPerNode *uint32                `protobuf:"varint,2,req,name=maxInstancesPerNode" json:"maxInstancesPerNode,omitempty"`
	AllowLocalRoutees   *bool                  `protobuf:"varint,3,req,name=allowLocalRoutees" json:"allowLocalRoutees,omitempty"`
	UseRole             *string                `protobuf:"bytes,4,opt,name=useRole" json:"useRole,omitempty"`
	UseRoles            []string               `protobuf:"bytes,5,rep,name=useRoles" json:"useRoles,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClusterRouterPoolSettings) Reset() {
	*x = ClusterRouterPoolSettings{}
	mi := &file_ClusterMessages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRouterPoolSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRouterPoolSettings) ProtoMessage() {}

func (x *ClusterRouterPoolSettings) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRouterPoolSettings.ProtoReflect.Descriptor instead.
func (*ClusterRouterPoolSettings) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{21}
}

func (x *ClusterRouterPoolSettings) GetTotalInstances() uint32 {
	if x != nil && x.TotalInstances != nil {
		return *x.TotalInstances
	}
	return 0
}

func (x *ClusterRouterPoolSettings) GetMaxInstancesPerNode() uint32 {
	if x != nil && x.MaxInstancesPerNode != nil {
		return *x.MaxInstancesPerNode
	}
	return 0
}

func (x *ClusterRouterPoolSettings) GetAllowLocalRoutees() bool {
	if x != nil && x.AllowLocalRoutees != nil {
		return *x.AllowLocalRoutees
	}
	return false
}

func (x *ClusterRouterPoolSettings) GetUseRole() string {
	if x != nil && x.UseRole != nil {
		return *x.UseRole
	}
	return ""
}

func (x *ClusterRouterPoolSettings) GetUseRoles() []string {
	if x != nil {
		return x.UseRoles
	}
	return nil
}

type VectorClock_Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashIndex     *int32                 `protobuf:"varint,1,req,name=hashIndex" json:"hashIndex,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock_Version) Reset() {
	*x = VectorClock_Version{}
	mi := &file_ClusterMessages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock_Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock_Version) ProtoMessage() {}

func (x *VectorClock_Version) ProtoReflect() protoreflect.Message {
	mi := &file_ClusterMessages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock_Version.ProtoReflect.Descriptor instead.
func (*VectorClock_Version) Descriptor() ([]byte, []int) {
	return file_ClusterMessages_proto_rawDescGZIP(), []int{15, 0}
}

func (x *VectorClock_Version) GetHashIndex() int32 {
	if x != nil && x.HashIndex != nil {
		return *x.HashIndex
	}
	return 0
}

func (x *VectorClock_Version) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_ClusterMessages_proto protoreflect.FileDescriptor

const file_ClusterMessages_proto_rawDesc = "" +
	"\n" +
	"\x15ClusterMessages.proto\x12\rpekko.cluster\"n\n" +
	"\x04Join\x120\n" +
	"\x04node\x18\x01 \x02(\v2\x1c.pekko.cluster.UniqueAddressR\x04node\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x03 \x01(\tR\n" +
	"appVersion\"j\n" +
	"\aWelcome\x120\n" +
	"\x04from\x18\x01 \x02(\v2\x1c.pekko.cluster.UniqueAddressR\x04from\x12-\n" +
	"\x06gossip\x18\x02 \x02(\v2\x15.pekko.cluster.GossipR\x06gossip\"0\n" +
	"\bInitJoin\x12$\n" +
	"\rcurrentConfig\x18\x01 \x01(\tR\rcurrentConfig\"}\n" +
	"\vInitJoinAck\x120\n" +
	"\aaddress\x18\x01 \x02(\v2\x16.pekko.cluster.AddressR\aaddress\x12<\n" +
	"\vconfigCheck\x18\x02 \x02(\v2\x1a.pekko.cluster.ConfigCheckR\vconfigCheck\"\xb3\x01\n" +
	"\vConfigCheck\x123\n" +
	"\x04type\x18\x01 \x02(\x0e2\x1f.pekko.cluster.ConfigCheck.TypeR\x04type\x12$\n" +
	"\rclusterConfig\x18\x02 \x01(\tR\rclusterConfig\"I\n" +
	"\x04Type\x12\x13\n" +
	"\x0fUncheckedConfig\x10\x01\x12\x16\n" +
	"\x12IncompatibleConfig\x10\x02\x12\x14\n" +
	"\x10CompatibleConfig\x10\x03\"{\n" +
	"\tHeartbeat\x12*\n" +
	"\x04from\x18\x01 \x02(\v2\x16.pekko.cluster.AddressR\x04from\x12\x1e\n" +
	"\n" +
	"sequenceNr\x18\x02 \x01(\x03R\n" +
	"sequenceNr\x12\"\n" +
	"\fcreationTime\x18\x03 \x01(\x12R\fcreationTime\"\x89\x01\n" +
	"\x11HeartBeatResponse\x120\n" +
	"\x04from\x18\x01 \x02(\v2\x1c.pekko.cluster.UniqueAddressR\x04from\x12\x1e\n" +
	"\n" +
	"sequenceNr\x18\x02 \x01(\x03R\n" +
	"sequenceNr\x12\"\n" +
	"\fcreationTime\x18\x03 \x01(\x03R\fcreationTime\"\x9c\x01\n" +
	"\x0eGossipEnvelope\x120\n" +
	"\x04from\x18\x01 \x02(\v2\x1c.pekko.cluster.UniqueAddressR\x04from\x12,\n" +
	"\x02to\x18\x02 \x02(\v2\x1c.pekko.cluster.UniqueAddressR\x02to\x12*\n" +
	"\x10serializedGossip\x18\x03 \x02(\fR\x10serializedGossip\"\xb4\x01\n" +
	"\fGossipStatus\x120\n" +
	"\x04from\x18\x01 \x02(\v2\x1c.pekko.cluster.UniqueAddressR\x04from\x12\x1c\n" +
	"\tallHashes\x18\x02 \x03(\tR\tallHashes\x124\n" +
	"\aversion\x18\x03 \x02(\v2\x1a.pekko.cluster.VectorClockR\aversion\x12\x1e\n" +
	"\n" +
	"seenDigest\x18\x04 \x01(\fR\n" +
	"seenDigest\"\x88\x03\n" +
	"\x06Gossip\x12@\n" +
	"\fallAddresses\x18\x01 \x03(\v2\x1c.pekko.cluster.UniqueAddressR\fallAddresses\x12\x1a\n" +
	"\ballRoles\x18\x02 \x03(\tR\ballRoles\x12\x1c\n" +
	"\tallHashes\x18\x03 \x03(\tR\tallHashes\x12/\n" +
	"\amembers\x18\x04 \x03(\v2\x15.pekko.cluster.MemberR\amembers\x129\n" +
	"\boverview\x18\x05 \x02(\v2\x1d.pekko.cluster.GossipOverviewR\boverview\x124\n" +
	"\aversion\x18\x06 \x02(\v2\x1a.pekko.cluster.VectorClockR\aversion\x128\n" +
	"\n" +
	"tombstones\x18\a \x03(\v2\x18.pekko.cluster.TombstoneR\n" +
	"tombstones\x12&\n" +
	"\x0eallAppVersions\x18\b \x03(\tR\x0eallAppVersions\"}\n" +
	"\x0eGossipOverview\x12\x12\n" +
	"\x04seen\x18\x01 \x03(\x05R\x04seen\x12W\n" +
	"\x14observerReachability\x18\x02 \x03(\v2#.pekko.cluster.ObserverReachabilityR\x14observerReachability\"\xaa\x01\n" +
	"\x14ObserverReachability\x12\"\n" +
	"\faddressIndex\x18\x01 \x02(\x05R\faddressIndex\x12\x18\n" +
	"\aversion\x18\x04 \x02(\x03R\aversion\x12T\n" +
	"\x13subjectReachability\x18\x02 \x03(\v2\".pekko.cluster.SubjectReachabilityR\x13subjectReachability\"\x8e\x01\n" +
	"\x13SubjectReachability\x12\"\n" +
	"\faddressIndex\x18\x01 \x02(\x05R\faddressIndex\x129\n" +
	"\x06status\x18\x03 \x02(\x0e2!.pekko.cluster.ReachabilityStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x02(\x03R\aversion\"M\n" +
	"\tTombstone\x12\"\n" +
	"\faddressIndex\x18\x01 \x02(\x05R\faddressIndex\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x02(\x03R\ttimestamp\"\xcf\x01\n" +
	"\x06Member\x12\"\n" +
	"\faddressIndex\x18\x01 \x02(\x05R\faddressIndex\x12\x1a\n" +
	"\bupNumber\x18\x02 \x02(\x05R\bupNumber\x123\n" +
	"\x06status\x18\x03 \x02(\x0e2\x1b.pekko.cluster.MemberStatusR\x06status\x12&\n" +
	"\frolesIndexes\x18\x04 \x03(\x05B\x02\x10\x01R\frolesIndexes\x12(\n" +
	"\x0fappVersionIndex\x18\x05 \x01(\x05R\x0fappVersionIndex\"\xb2\x01\n" +
	"\vVectorClock\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12>\n" +
	"\bversions\x18\x02 \x03(\v2\".pekko.cluster.VectorClock.VersionR\bversions\x1aE\n" +
	"\aVersion\x12\x1c\n" +
	"\thashIndex\x18\x01 \x02(\x05R\thashIndex\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x02(\x03R\ttimestamp\"\a\n" +
	"\x05Empty\"m\n" +
	"\aAddress\x12\x16\n" +
	"\x06system\x18\x01 \x02(\tR\x06system\x12\x1a\n" +
	"\bhostname\x18\x02 \x02(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x02(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"g\n" +
	"\rUniqueAddress\x120\n" +
	"\aaddress\x18\x01 \x02(\v2\x16.pekko.cluster.AddressR\aaddress\x12\x10\n" +
	"\x03uid\x18\x02 \x02(\rR\x03uid\x12\x12\n" +
	"\x04uid2\x18\x03 \x01(\rR\x04uid2\"\x82\x01\n" +
	"\x11ClusterRouterPool\x12'\n" +
	"\x04pool\x18\x01 \x02(\v2\x13.pekko.cluster.PoolR\x04pool\x12D\n" +
	"\bsettings\x18\x02 \x02(\v2(.pekko.cluster.ClusterRouterPoolSettingsR\bsettings\"Z\n" +
	"\x04Pool\x12\"\n" +
	"\fserializerId\x18\x01 \x02(\rR\fserializerId\x12\x1a\n" +
	"\bmanifest\x18\x02 \x02(\tR\bmanifest\x12\x12\n" +
	"\x04data\x18\x03 \x02(\fR\x04data\"\xd9\x01\n" +
	"\x19ClusterRouterPoolSettings\x12&\n" +
	"\x0etotalInstances\x18\x01 \x02(\rR\x0etotalInstances\x120\n" +
	"\x13maxInstancesPerNode\x18\x02 \x02(\rR\x13maxInstancesPerNode\x12,\n" +
	"\x11allowLocalRoutees\x18\x03 \x02(\bR\x11allowLocalRoutees\x12\x18\n" +
	"\auseRole\x18\x04 \x01(\tR\auseRole\x12\x1a\n" +
	"\buseRoles\x18\x05 \x03(\tR\buseRoles*D\n" +
	"\x12ReachabilityStatus\x12\r\n" +
	"\tReachable\x10\x00\x12\x0f\n" +
	"\vUnreachable\x10\x01\x12\x0e\n" +
	"\n" +
	"Terminated\x10\x02*\x92\x01\n" +
	"\fMemberStatus\x12\v\n" +
	"\aJoining\x10\x00\x12\x06\n" +
	"\x02Up\x10\x01\x12\v\n" +
	"\aLeaving\x10\x02\x12\v\n" +
	"\aExiting\x10\x03\x12\b\n" +
	"\x04Down\x10\x04\x12\v\n" +
	"\aRemoved\x10\x05\x12\f\n" +
	"\bWeaklyUp\x10\x06\x12\x18\n" +
	"\x14PreparingForShutdown\x10\a\x12\x14\n" +
	"\x10ReadyForShutdown\x10\bB)\n" +
	"%org.apache.pekko.cluster.protobuf.msgH\x01"

var (
	file_ClusterMessages_proto_rawDescOnce sync.Once
	file_ClusterMessages_proto_rawDescData []byte
)

func file_ClusterMessages_proto_rawDescGZIP() []byte {
	file_ClusterMessages_proto_rawDescOnce.Do(func() {
		file_ClusterMessages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ClusterMessages_proto_rawDesc), len(file_ClusterMessages_proto_rawDesc)))
	})
	return file_ClusterMessages_proto_rawDescData
}

var file_ClusterMessages_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ClusterMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ClusterMessages_proto_goTypes = []any{
	(ReachabilityStatus)(0),           // 0: pekko.cluster.ReachabilityStatus
	(MemberStatus)(0),                 // 1: pekko.cluster.MemberStatus
	(ConfigCheck_Type)(0),             // 2: pekko.cluster.ConfigCheck.Type
	(*Join)(nil),                      // 3: pekko.cluster.Join
	(*Welcome)(nil),                   // 4: pekko.cluster.Welcome
	(*InitJoin)(nil),                  // 5: pekko.cluster.InitJoin
	(*InitJoinAck)(nil),               // 6: pekko.cluster.InitJoinAck
	(*ConfigCheck)(nil),               // 7: pekko.cluster.ConfigCheck
	(*Heartbeat)(nil),                 // 8: pekko.cluster.Heartbeat
	(*HeartBeatResponse)(nil),         // 9: pekko.cluster.HeartBeatResponse
	(*GossipEnvelope)(nil),            // 10: pekko.cluster.GossipEnvelope
	(*GossipStatus)(nil),              // 11: pekko.cluster.GossipStatus
	(*Gossip)(nil),                    // 12: pekko.cluster.Gossip
	(*GossipOverview)(nil),            // 13: pekko.cluster.GossipOverview
	(*ObserverReachability)(nil),      // 14: pekko.cluster.ObserverReachability
	(*SubjectReachability)(nil),       // 15: pekko.cluster.SubjectReachability
	(*Tombstone)(nil),                 // 16: pekko.cluster.Tombstone
	(*Member)(nil),                    // 17: pekko.cluster.Member
	(*VectorClock)(nil),               // 18: pekko.cluster.VectorClock
	(*Empty)(nil),                     // 19: pekko.cluster.Empty
	(*Address)(nil),                   // 20: pekko.cluster.Address
	(*UniqueAddress)(nil),             // 21: pekko.cluster.UniqueAddress
	(*ClusterRouterPool)(nil),         // 22: pekko.cluster.ClusterRouterPool
	(*Pool)(nil),                      // 23: pekko.cluster.Pool
	(*ClusterRouterPoolSettings)(nil), // 24: pekko.cluster.ClusterRouterPoolSettings
	(*VectorClock_Version)(nil),       // 25: pekko.cluster.VectorClock.Version
}
var file_ClusterMessages_proto_depIdxs = []int32{
	21, // 0: pekko.cluster.Join.node:type_name -> pekko.cluster.UniqueAddress
	21, // 1: pekko.cluster.Welcome.from:type_name -> pekko.cluster.UniqueAddress
	12, // 2: pekko.cluster.Welcome.gossip:type_name -> pekko.cluster.Gossip
	20, // 3: pekko.cluster.InitJoinAck.address:type_name -> pekko.cluster.Address
	7,  // 4: pekko.cluster.InitJoinAck.configCheck:type_name -> pekko.cluster.ConfigCheck
	2,  // 5: pekko.cluster.ConfigCheck.type:type_name -> pekko.cluster.ConfigCheck.Type
	20, // 6: pekko.cluster.Heartbeat.from:type_name -> pekko.cluster.Address
	21, // 7: pekko.cluster.HeartBeatResponse.from:type_name -> pekko.cluster.UniqueAddress
	21, // 8: pekko.cluster.GossipEnvelope.from:type_name -> pekko.cluster.UniqueAddress
	21, // 9: pekko.cluster.GossipEnvelope.to:type_name -> pekko.cluster.UniqueAddress
	21, // 10: pekko.cluster.GossipStatus.from:type_name -> pekko.cluster.UniqueAddress
	18, // 11: pekko.cluster.GossipStatus.version:type_name -> pekko.cluster.VectorClock
	21, // 12: pekko.cluster.Gossip.allAddresses:type_name -> pekko.cluster.UniqueAddress
	17, // 13: pekko.cluster.Gossip.members:type_name -> pekko.cluster.Member
	13, // 14: pekko.cluster.Gossip.overview:type_name -> pekko.cluster.GossipOverview
	18, // 15: pekko.cluster.Gossip.version:type_name -> pekko.cluster.VectorClock
	16, // 16: pekko.cluster.Gossip.tombstones:type_name -> pekko.cluster.Tombstone
	14, // 17: pekko.cluster.GossipOverview.observerReachability:type_name -> pekko.cluster.ObserverReachability
	15, // 18: pekko.cluster.ObserverReachability.subjectReachability:type_name -> pekko.cluster.SubjectReachability
	0,  // 19: pekko.cluster.SubjectReachability.status:type_name -> pekko.cluster.ReachabilityStatus
	1,  // 20: pekko.cluster.Member.status:type_name -> pekko.cluster.MemberStatus
	25, // 21: pekko.cluster.VectorClock.versions:type_name -> pekko.cluster.VectorClock.Version
	20, // 22: pekko.cluster.UniqueAddress.address:type_name -> pekko.cluster.Address
	23, // 23: pekko.cluster.ClusterRouterPool.pool:type_name -> pekko.cluster.Pool
	24, // 24: pekko.cluster.ClusterRouterPool.settings:type_name -> pekko.cluster.ClusterRouterPoolSettings
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_ClusterMessages_proto_init() }
func file_ClusterMessages_proto_init() {
	if File_ClusterMessages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ClusterMessages_proto_rawDesc), len(file_ClusterMessages_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ClusterMessages_proto_goTypes,
		DependencyIndexes: file_ClusterMessages_proto_depIdxs,
		EnumInfos:         file_ClusterMessages_proto_enumTypes,
		MessageInfos:      file_ClusterMessages_proto_msgTypes,
	}.Build()
	File_ClusterMessages_proto = out.File
	file_ClusterMessages_proto_goTypes = nil
	file_ClusterMessages_proto_depIdxs = nil
}
