/*
 * cluster/pubsub_compatibility_test.go
 * This file is part of the gekka project.
 *
 * Copyright (c) 2026 Sopranoworks, Osamu Takahashi
 * SPDX-License-Identifier: MIT
 */

// Package cluster_test verifies that the binary wire format produced by
// cluster/pubsub matches Pekko's DistributedPubSubMessageSerializer exactly,
// using binary fixtures generated by the real JVM serializer.
//
// Fixtures are generated by:
//
//	cd scala-server && sbt "runMain org.apache.pekko.cluster.pubsub.PubSubBinaryGenerator ../cluster/testdata"
//
// Wire format reference (Pekko source):
//
//	cluster-tools/src/main/scala/org/apache/pekko/cluster/pubsub/protobuf/DistributedPubSubMessageSerializer.scala
//	cluster-tools/src/main/protobuf/DistributedPubSubMessages.proto
//
// Pekko serializer ID: 9
// Manifests: "A"=Status(GZIP), "B"=Delta(GZIP), "C"=Send, "D"=SendToAll, "E"=Publish, "F"=SendToOneSubscriber
//
// Test fixture contents (from Scala generator):
//
//	pubsub_publish.bin              Publish("news", "Hello" as bytes)          17 bytes
//	pubsub_send.bin                 Send("/user/handler", [1,2,3,4], true)     27 bytes
//	pubsub_sendtoall.bin            SendToAll("/user/all", [5,6,7], false)     22 bytes
//	pubsub_sendtoonesubscriber.bin  SendToOneSubscriber([9,10,11])             9 bytes
//	pubsub_status.bin               Status(Map(addr->42), replyToStatus=true)  56 bytes GZIP
//	pubsub_delta.bin                Delta(Bucket(addr,3,{"/news"->VH(2,"")}))  65 bytes GZIP
//
// ID 9 conflict note:
//
//	Pekko assigns ID 9 to DistributedPubSubMessageSerializer.
//	Gekka's internal JSONSerializer also uses ID 9 for CRDT gossip between Go-only nodes.
//	Enabling Pekko pub-sub interop requires registering PubSubSerializer at ID 9,
//	superseding the JSON serializer in the SerializationRegistry for that node.
package cluster_test

import (
	"bytes"
	"compress/gzip"
	"io"
	"os"
	"testing"

	"github.com/sopranoworks/gekka/cluster/pubsub"
)

const fixtureDir = "testdata"

// loadFixture reads a binary fixture from the testdata directory.
// The test is skipped — not failed — if the fixture has not yet been generated,
// with instructions for how to produce it.
func loadFixture(t *testing.T, name string) []byte {
	t.Helper()
	path := fixtureDir + "/" + name
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skipf(
				"fixture %q not found — generate with:\n"+
					"  cd scala-server && sbt \"runMain org.apache.pekko.cluster.pubsub.PubSubBinaryGenerator ../cluster/testdata\"",
				path,
			)
		}
		t.Fatalf("loadFixture %s: %v", path, err)
	}
	return data
}

// gzipDecompress decompresses GZIP data, used to compare inner proto bytes.
func gzipDecompress(data []byte) ([]byte, error) {
	r, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		return nil, err
	}
	defer r.Close()
	return io.ReadAll(r)
}

// isGzip returns true if data starts with the GZIP magic bytes.
func isGzip(data []byte) bool {
	return len(data) >= 2 && data[0] == 0x1f && data[1] == 0x8b
}

// ---------------------------------------------------------------------------
// Serializer ID and manifest constants
// ---------------------------------------------------------------------------

// TestPubSubSerializerID verifies the serializer ID matches Pekko's assignment.
//
// Source: cluster-tools/src/main/resources/reference.conf
//
//	serialization-identifiers {
//	  "org.apache.pekko.cluster.pubsub.protobuf.DistributedPubSubMessageSerializer" = 9
//	}
func TestPubSubSerializerID(t *testing.T) {
	const want = int32(9)
	if pubsub.PubSubSerializerID != want {
		t.Errorf("PubSubSerializerID = %d, want %d", pubsub.PubSubSerializerID, want)
	}
}

// TestPubSubManifests verifies all six manifest codes match Pekko exactly.
// Source: DistributedPubSubMessageSerializer.scala, StatusManifest through SendToOneSubscriberManifest.
func TestPubSubManifests(t *testing.T) {
	cases := []struct{ name, got, want string }{
		{"Status", pubsub.StatusManifest, "A"},
		{"Delta", pubsub.DeltaManifest, "B"},
		{"Send", pubsub.SendManifest, "C"},
		{"SendToAll", pubsub.SendToAllManifest, "D"},
		{"Publish", pubsub.PublishManifest, "E"},
		{"SendToOneSubscriber", pubsub.SendToOneSubscriberManifest, "F"},
	}
	for _, c := range cases {
		if c.got != c.want {
			t.Errorf("%s manifest = %q, want %q", c.name, c.got, c.want)
		}
	}
}

// ---------------------------------------------------------------------------
// Publish (manifest "E") — plain Protobuf, 17 bytes
//
// Proto schema:
//   message Publish {
//     required string topic   = 1;
//     required Payload payload = 3;   // field 3, not 2
//   }
//
// Fixture: Publish("news", Array[Byte]("Hello")), payload via ByteArraySerializer (ID=4)
// ---------------------------------------------------------------------------

// TestPublish_ScalaDecode verifies Go can decode Pekko-generated Publish bytes.
func TestPublish_ScalaDecode(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_publish.bin")

	if isGzip(scalaBytes) {
		t.Fatal("Publish fixture must NOT be GZIP-compressed (Pekko sends plain Protobuf for Publish)")
	}

	s := &pubsub.PubSubSerializer{}
	topic, msg, serializerID, manifest, err := s.DecodePublish(scalaBytes)
	if err != nil {
		t.Fatalf("DecodePublish: %v", err)
	}
	if topic != "news" {
		t.Errorf("topic = %q, want %q", topic, "news")
	}
	if !bytes.Equal(msg, []byte("Hello")) {
		t.Errorf("enclosedMessage = %v, want %q", msg, "Hello")
	}
	if serializerID != 4 {
		t.Errorf("serializerID = %d, want 4 (ByteArraySerializer)", serializerID)
	}
	if manifest != "" {
		t.Errorf("manifest = %q, want empty (ByteArraySerializer.includeManifest=false)", manifest)
	}
}

// TestPublish_GoMatchesScala verifies Go-encoded bytes are identical to Pekko's output.
// This is a strict byte-level comparison for plain Protobuf (no GZIP non-determinism).
func TestPublish_GoMatchesScala(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_publish.bin")

	s := &pubsub.PubSubSerializer{}
	goBytes, err := s.EncodePublish("news", []byte("Hello"), 4, "")
	if err != nil {
		t.Fatalf("EncodePublish: %v", err)
	}

	if !bytes.Equal(goBytes, scalaBytes) {
		t.Errorf("Go-encoded Publish does NOT match Pekko output:\n  Go  (%d bytes): %x\n  JVM (%d bytes): %x",
			len(goBytes), goBytes, len(scalaBytes), scalaBytes)
	}
}

// TestPublish_PayloadAtFieldThree verifies the payload is at proto field 3, not field 2.
// This is a critical correctness check — DistributedPubSubMessages.proto defines:
//
//	message Publish {
//	  required string topic   = 1;
//	  required Payload payload = 3;   // field 3!
//	}
func TestPublish_PayloadAtFieldThree(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_publish.bin")
	// Layout: 0x0a <len> "news" <tag> ...
	// After "0a 04 news" (6 bytes), the next tag byte must be 0x1a = (3<<3)|2
	if len(scalaBytes) < 7 {
		t.Fatalf("fixture too short: %v", scalaBytes)
	}
	topicTagLen := 2 + 4 // tag + len-byte + "news"
	payloadTag := scalaBytes[topicTagLen]
	const want = byte(0x1a) // field 3, wireBytes
	if payloadTag != want {
		t.Errorf("payload tag = 0x%02x, want 0x1a (field 3, wireBytes); "+
			"Pekko's Publish proto defines payload at field 3", payloadTag)
	}
}

// ---------------------------------------------------------------------------
// Send (manifest "C") — plain Protobuf, 27 bytes
//
// Proto schema:
//   message Send {
//     required string path        = 1;
//     required bool localAffinity = 2;
//     required Payload payload    = 3;
//   }
//
// Fixture: Send("/user/handler", Array[Byte](1,2,3,4), localAffinity=true)
// ---------------------------------------------------------------------------

func TestSend_ScalaDecode(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_send.bin")

	if isGzip(scalaBytes) {
		t.Fatal("Send fixture must NOT be GZIP-compressed")
	}

	s := &pubsub.PubSubSerializer{}
	path, localAffinity, msg, serializerID, manifest, err := s.DecodeSend(scalaBytes)
	if err != nil {
		t.Fatalf("DecodeSend: %v", err)
	}
	if path != "/user/handler" {
		t.Errorf("path = %q, want /user/handler", path)
	}
	if !localAffinity {
		t.Error("localAffinity should be true")
	}
	if !bytes.Equal(msg, []byte{1, 2, 3, 4}) {
		t.Errorf("enclosedMessage = %v, want [1 2 3 4]", msg)
	}
	if serializerID != 4 {
		t.Errorf("serializerID = %d, want 4", serializerID)
	}
	if manifest != "" {
		t.Errorf("manifest = %q, want empty", manifest)
	}
}

func TestSend_GoMatchesScala(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_send.bin")

	s := &pubsub.PubSubSerializer{}
	goBytes, err := s.EncodeSend("/user/handler", true, []byte{1, 2, 3, 4}, 4, "")
	if err != nil {
		t.Fatalf("EncodeSend: %v", err)
	}

	if !bytes.Equal(goBytes, scalaBytes) {
		t.Errorf("Go-encoded Send does NOT match Pekko output:\n  Go  (%d bytes): %x\n  JVM (%d bytes): %x",
			len(goBytes), goBytes, len(scalaBytes), scalaBytes)
	}
}

// ---------------------------------------------------------------------------
// SendToAll (manifest "D") — plain Protobuf, 22 bytes
//
// Proto schema:
//   message SendToAll {
//     required string path     = 1;
//     required bool allButSelf = 2;
//     required Payload payload = 3;
//   }
//
// Fixture: SendToAll("/user/all", Array[Byte](5,6,7), allButSelf=false)
// Note: allButSelf=false is a proto2 required field, so Pekko always encodes it (0x10 0x00).
// ---------------------------------------------------------------------------

func TestSendToAll_ScalaDecode(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_sendtoall.bin")

	if isGzip(scalaBytes) {
		t.Fatal("SendToAll fixture must NOT be GZIP-compressed")
	}

	s := &pubsub.PubSubSerializer{}
	path, allButSelf, msg, serializerID, manifest, err := s.DecodeSendToAll(scalaBytes)
	if err != nil {
		t.Fatalf("DecodeSendToAll: %v", err)
	}
	if path != "/user/all" {
		t.Errorf("path = %q, want /user/all", path)
	}
	if allButSelf {
		t.Error("allButSelf should be false")
	}
	if !bytes.Equal(msg, []byte{5, 6, 7}) {
		t.Errorf("enclosedMessage = %v, want [5 6 7]", msg)
	}
	if serializerID != 4 {
		t.Errorf("serializerID = %d, want 4", serializerID)
	}
	if manifest != "" {
		t.Errorf("manifest = %q, want empty", manifest)
	}
}

func TestSendToAll_GoMatchesScala(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_sendtoall.bin")

	s := &pubsub.PubSubSerializer{}
	goBytes, err := s.EncodeSendToAll("/user/all", false, []byte{5, 6, 7}, 4, "")
	if err != nil {
		t.Fatalf("EncodeSendToAll: %v", err)
	}

	if !bytes.Equal(goBytes, scalaBytes) {
		t.Errorf("Go-encoded SendToAll does NOT match Pekko output:\n  Go  (%d bytes): %x\n  JVM (%d bytes): %x",
			len(goBytes), goBytes, len(scalaBytes), scalaBytes)
	}
}

// ---------------------------------------------------------------------------
// SendToOneSubscriber (manifest "F") — plain Protobuf, 9 bytes
//
// Proto schema:
//   message SendToOneSubscriber {
//     required Payload payload = 1;
//   }
//
// Fixture: SendToOneSubscriber(Array[Byte](9,10,11))
// ---------------------------------------------------------------------------

func TestSendToOneSubscriber_ScalaDecode(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_sendtoonesubscriber.bin")

	if isGzip(scalaBytes) {
		t.Fatal("SendToOneSubscriber fixture must NOT be GZIP-compressed")
	}

	s := &pubsub.PubSubSerializer{}
	msg, serializerID, manifest, err := s.DecodeSendToOneSubscriber(scalaBytes)
	if err != nil {
		t.Fatalf("DecodeSendToOneSubscriber: %v", err)
	}
	if !bytes.Equal(msg, []byte{9, 10, 11}) {
		t.Errorf("enclosedMessage = %v, want [9 10 11]", msg)
	}
	if serializerID != 4 {
		t.Errorf("serializerID = %d, want 4", serializerID)
	}
	if manifest != "" {
		t.Errorf("manifest = %q, want empty", manifest)
	}
}

func TestSendToOneSubscriber_GoMatchesScala(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_sendtoonesubscriber.bin")

	s := &pubsub.PubSubSerializer{}
	goBytes, err := s.EncodeSendToOneSubscriber([]byte{9, 10, 11}, 4, "")
	if err != nil {
		t.Fatalf("EncodeSendToOneSubscriber: %v", err)
	}

	if !bytes.Equal(goBytes, scalaBytes) {
		t.Errorf("Go-encoded SendToOneSubscriber does NOT match Pekko output:\n  Go  (%d bytes): %x\n  JVM (%d bytes): %x",
			len(goBytes), goBytes, len(scalaBytes), scalaBytes)
	}
}

// ---------------------------------------------------------------------------
// Status (manifest "A") — GZIP-compressed Protobuf, 56 bytes
//
// Proto schema:
//   message Status {
//     repeated Version versions    = 1;  // Version{ Address, int64 }
//     optional bool replyToStatus  = 2;
//   }
//
// Fixture: Status(Map(Address("pekko","TestSys","127.0.0.1",2551) -> 42L), replyToStatus=true)
//
// Because GZIP output is non-deterministic across JVM/Go implementations
// (different Deflate engines may produce different compressed bytes for the same input),
// the byte-level comparison is performed on the DECOMPRESSED inner proto bytes, which
// ARE deterministic for a single-entry map with a fully deterministic field order.
// ---------------------------------------------------------------------------

func TestStatus_ScalaIsGzip(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_status.bin")
	if !isGzip(scalaBytes) {
		t.Error("Status fixture must be GZIP-compressed (Pekko's compress() call)")
	}
}

func TestStatus_ScalaDecode(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_status.bin")

	s := &pubsub.PubSubSerializer{}
	st, err := s.DecodeStatus(scalaBytes)
	if err != nil {
		t.Fatalf("DecodeStatus: %v", err)
	}

	if len(st.Versions) != 1 {
		t.Fatalf("Versions len = %d, want 1", len(st.Versions))
	}
	if !st.IsReplyToStatus {
		t.Error("IsReplyToStatus should be true")
	}

	for addr, ts := range st.Versions {
		if addr.System != "TestSys" {
			t.Errorf("addr.System = %q, want TestSys", addr.System)
		}
		if addr.Hostname != "127.0.0.1" {
			t.Errorf("addr.Hostname = %q, want 127.0.0.1", addr.Hostname)
		}
		if addr.Port != 2551 {
			t.Errorf("addr.Port = %d, want 2551", addr.Port)
		}
		if addr.Protocol != "pekko" {
			t.Errorf("addr.Protocol = %q, want pekko", addr.Protocol)
		}
		if ts != 42 {
			t.Errorf("timestamp = %d, want 42", ts)
		}
	}
}

// TestStatus_InnerProtoMatchesScala compares the decompressed inner proto bytes.
// GZIP bytes from JVM and Go may differ (different Deflate engines); the inner
// proto bytes must be identical for the same message.
func TestStatus_InnerProtoMatchesScala(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_status.bin")

	// Decode the Scala fixture to recover the Status value.
	s := &pubsub.PubSubSerializer{}
	st, err := s.DecodeStatus(scalaBytes)
	if err != nil {
		t.Fatalf("DecodeStatus (scala): %v", err)
	}

	// Re-encode with Go serializer.
	goBytes, err := s.EncodeStatus(st)
	if err != nil {
		t.Fatalf("EncodeStatus (go): %v", err)
	}

	// Decompress both and compare inner proto bytes.
	scalaProto, err := gzipDecompress(scalaBytes)
	if err != nil {
		t.Fatalf("gzipDecompress(scala): %v", err)
	}
	goProto, err := gzipDecompress(goBytes)
	if err != nil {
		t.Fatalf("gzipDecompress(go): %v", err)
	}

	if !bytes.Equal(goProto, scalaProto) {
		t.Errorf("Inner proto bytes mismatch (GZIP wrappers may differ between JVM/Go):\n"+
			"  Go  (%d bytes): %x\n"+
			"  JVM (%d bytes): %x",
			len(goProto), goProto, len(scalaProto), scalaProto)
	}
}

// ---------------------------------------------------------------------------
// Delta (manifest "B") — GZIP-compressed Protobuf, 65 bytes
//
// Proto schema:
//   message Delta {
//     repeated Bucket buckets = 1;
//     message Entry  { required string key=1; required int64 version=2; optional string ref=3; }
//     message Bucket { required Address owner=1; required int64 version=2; repeated Entry content=3; }
//   }
//
// Fixture: Delta(List(Bucket(testAddr, 3, TreeMap("/news" -> ValueHolder(2, None)))))
// None ref means field 3 (ref) is absent from the Entry proto.
// ---------------------------------------------------------------------------

func TestDelta_ScalaIsGzip(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_delta.bin")
	if !isGzip(scalaBytes) {
		t.Error("Delta fixture must be GZIP-compressed (Pekko's compress() call)")
	}
}

func TestDelta_ScalaDecode(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_delta.bin")

	s := &pubsub.PubSubSerializer{}
	d, err := s.DecodeDelta(scalaBytes)
	if err != nil {
		t.Fatalf("DecodeDelta: %v", err)
	}

	if len(d.Buckets) != 1 {
		t.Fatalf("Buckets len = %d, want 1", len(d.Buckets))
	}
	b := d.Buckets[0]
	if b.Owner.System != "TestSys" {
		t.Errorf("Bucket.Owner.System = %q, want TestSys", b.Owner.System)
	}
	if b.Owner.Hostname != "127.0.0.1" {
		t.Errorf("Bucket.Owner.Hostname = %q, want 127.0.0.1", b.Owner.Hostname)
	}
	if b.Owner.Port != 2551 {
		t.Errorf("Bucket.Owner.Port = %d, want 2551", b.Owner.Port)
	}
	if b.Owner.Protocol != "pekko" {
		t.Errorf("Bucket.Owner.Protocol = %q, want pekko", b.Owner.Protocol)
	}
	if b.Version != 3 {
		t.Errorf("Bucket.Version = %d, want 3", b.Version)
	}
	if len(b.Content) != 1 {
		t.Fatalf("Bucket.Content len = %d, want 1", len(b.Content))
	}
	vh, ok := b.Content["/news"]
	if !ok {
		t.Fatal("missing /news entry in Bucket.Content")
	}
	if vh.Version != 2 {
		t.Errorf("/news.version = %d, want 2", vh.Version)
	}
	if vh.Ref != "" {
		t.Errorf("/news.ref = %q, want empty (None in Scala → absent field 3 in proto)", vh.Ref)
	}
}

// TestDelta_InnerProtoMatchesScala compares decompressed inner proto bytes.
func TestDelta_InnerProtoMatchesScala(t *testing.T) {
	scalaBytes := loadFixture(t, "pubsub_delta.bin")

	s := &pubsub.PubSubSerializer{}
	d, err := s.DecodeDelta(scalaBytes)
	if err != nil {
		t.Fatalf("DecodeDelta (scala): %v", err)
	}

	goBytes, err := s.EncodeDelta(d)
	if err != nil {
		t.Fatalf("EncodeDelta (go): %v", err)
	}

	scalaProto, err := gzipDecompress(scalaBytes)
	if err != nil {
		t.Fatalf("gzipDecompress(scala): %v", err)
	}
	goProto, err := gzipDecompress(goBytes)
	if err != nil {
		t.Fatalf("gzipDecompress(go): %v", err)
	}

	if !bytes.Equal(goProto, scalaProto) {
		t.Errorf("Inner proto bytes mismatch:\n  Go  (%d bytes): %x\n  JVM (%d bytes): %x",
			len(goProto), goProto, len(scalaProto), scalaProto)
	}
}

// ---------------------------------------------------------------------------
// Compression boundary: exactly which messages are GZIP'd
// Verified against actual Pekko output, not just spec comments.
// ---------------------------------------------------------------------------

// TestCompressionBoundary_FromFixtures asserts GZIP presence/absence for all
// six message types by inspecting the actual Scala-generated fixture files.
func TestCompressionBoundary_FromFixtures(t *testing.T) {
	cases := []struct {
		fixture string
		gzipped bool
		note    string
	}{
		{"pubsub_status.bin", true, "Status manifest A: compress(statusToProto(m))"},
		{"pubsub_delta.bin", true, "Delta manifest B: compress(deltaToProto(m))"},
		{"pubsub_send.bin", false, "Send manifest C: sendToProto(m).toByteArray"},
		{"pubsub_sendtoall.bin", false, "SendToAll manifest D: sendToAllToProto(m).toByteArray"},
		{"pubsub_publish.bin", false, "Publish manifest E: publishToProto(m).toByteArray"},
		{"pubsub_sendtoonesubscriber.bin", false, "SendToOneSubscriber manifest F: .toByteArray"},
	}
	for _, c := range cases {
		t.Run(c.fixture, func(t *testing.T) {
			data := loadFixture(t, c.fixture)
			if isGzip(data) != c.gzipped {
				if c.gzipped {
					t.Errorf("%s: expected GZIP-compressed (%s)", c.fixture, c.note)
				} else {
					t.Errorf("%s: expected plain Protobuf — NOT GZIP (%s)", c.fixture, c.note)
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Round-trip sanity: Go encodes → Go decodes → values match original
// (Independent of Scala fixtures; verifies internal consistency)
// ---------------------------------------------------------------------------

func TestPublish_RoundTrip(t *testing.T) {
	s := &pubsub.PubSubSerializer{}
	enc, err := s.EncodePublish("events", []byte{0xde, 0xad, 0xbe, 0xef}, 2, "MyProto")
	if err != nil {
		t.Fatalf("EncodePublish: %v", err)
	}
	topic, msg, id, manifest, err := s.DecodePublish(enc)
	if err != nil {
		t.Fatalf("DecodePublish: %v", err)
	}
	if topic != "events" || !bytes.Equal(msg, []byte{0xde, 0xad, 0xbe, 0xef}) || id != 2 || manifest != "MyProto" {
		t.Errorf("round-trip mismatch: topic=%q msg=%v id=%d manifest=%q", topic, msg, id, manifest)
	}
}

func TestStatus_RoundTrip(t *testing.T) {
	s := &pubsub.PubSubSerializer{}
	st := pubsub.Status{
		Versions: map[pubsub.Address]int64{
			{System: "sys", Hostname: "h1", Port: 2551, Protocol: "pekko"}: 99,
		},
		IsReplyToStatus: false,
	}
	enc, err := s.EncodeStatus(st)
	if err != nil {
		t.Fatalf("EncodeStatus: %v", err)
	}
	got, err := s.DecodeStatus(enc)
	if err != nil {
		t.Fatalf("DecodeStatus: %v", err)
	}
	if got.IsReplyToStatus != false || len(got.Versions) != 1 {
		t.Errorf("round-trip mismatch: %+v", got)
	}
}

func TestDelta_EmptyRef_RoundTrip(t *testing.T) {
	s := &pubsub.PubSubSerializer{}
	d := pubsub.Delta{
		Buckets: []pubsub.Bucket{
			{
				Owner:   pubsub.Address{System: "s", Hostname: "h", Port: 1, Protocol: "pekko"},
				Version: 7,
				Content: map[string]pubsub.ValueHolder{
					"/topic": {Version: 3, Ref: ""},                       // None in Scala
					"/group": {Version: 5, Ref: "pekko://s@h:1/user/sub"}, // Some(ref) in Scala
				},
			},
		},
	}
	enc, err := s.EncodeDelta(d)
	if err != nil {
		t.Fatalf("EncodeDelta: %v", err)
	}
	got, err := s.DecodeDelta(enc)
	if err != nil {
		t.Fatalf("DecodeDelta: %v", err)
	}
	if len(got.Buckets) != 1 || len(got.Buckets[0].Content) != 2 {
		t.Fatalf("round-trip mismatch: %+v", got)
	}
	if vh := got.Buckets[0].Content["/topic"]; vh.Ref != "" {
		t.Errorf("/topic Ref = %q, want empty", vh.Ref)
	}
	if vh := got.Buckets[0].Content["/group"]; vh.Ref != "pekko://s@h:1/user/sub" {
		t.Errorf("/group Ref = %q, want actor path", vh.Ref)
	}
}
