pekko {
  loglevel = "INFO"
  actor {
    provider = cluster
    debug {
      receive = off
    }
  }
  remote.artery {
    transport = tcp
    canonical {
      hostname = "127.0.0.1"
      port = 2552
    }
  }
  cluster {
    seed-nodes = ["pekko://ClusterSystem@127.0.0.1:2552"]
    min-nr-of-members = 1
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
    split-brain-resolver {
      active-strategy = keep-oldest
      stable-after = 5s
    }
    failure-detector {
      acceptable-heartbeat-pause = 15s
      heartbeat-interval = 1s
    }
  }
}
