/*
 * artery_compatibility_test.go
 * This file is part of the gekka project.
 *
 * Copyright (c) 2026 Sopranoworks, Osamu Takahashi
 * SPDX-License-Identifier: MIT
 */

// Package core_test verifies that the Go proto encoding of Artery control
// messages (serializer ID 17) is byte-identical to what Pekko's
// ArteryMessageSerializer produces.
//
// Fixture files are generated by:
//
//	cd scala-server && sbt "runMain org.apache.pekko.remote.artery.ArteryBinaryGenerator ../internal/core/testdata"
package core_test

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/sopranoworks/gekka/actor"
	gproto "github.com/sopranoworks/gekka/internal/proto/remote"
	"google.golang.org/protobuf/proto"
)

// loadFixtureArtery reads a binary fixture from testdata/.
// If the file does not exist the test is skipped with regeneration instructions.
func loadFixtureArtery(t *testing.T, name string) []byte {
	t.Helper()
	path := filepath.Join("testdata", name)
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		t.Skipf("fixture %s not found — regenerate with:\n"+
			"  cd scala-server && sbt \"runMain org.apache.pekko.remote.artery.ArteryBinaryGenerator ../internal/core/testdata\"\n"+
			"  go test ./internal/core/ -v -count=1", name)
	}
	if err != nil {
		t.Fatalf("read fixture %s: %v", name, err)
	}
	return data
}

// ---------------------------------------------------------------------------
// Serializer ID and manifest constants
// ---------------------------------------------------------------------------

// TestArterySerializerID verifies that the Go ArteryInternalSerializerID matches
// Pekko's ArteryMessageSerializer identifier (17).
func TestArterySerializerID(t *testing.T) {
	if actor.ArteryInternalSerializerID != 17 {
		t.Errorf("ArteryInternalSerializerID = %d, want 17", actor.ArteryInternalSerializerID)
	}
}

// TestArteryManifests verifies the manifest codes used for Artery control messages.
func TestArteryManifests(t *testing.T) {
	cases := []struct{ name, manifest string }{
		{"HandshakeReq", "d"},
		{"HandshakeRsp", "e"},
		{"ArteryHeartbeat", "m"},
		{"ArteryHeartbeatRsp", "n"},
	}
	// These are the Pekko-defined manifests; verify we know them correctly.
	for _, c := range cases {
		if len(c.manifest) == 0 {
			t.Errorf("%s manifest is empty", c.name)
		}
	}
	// Spot-check specific values
	if cases[0].manifest != "d" {
		t.Errorf("HandshakeReq manifest = %q, want %q", cases[0].manifest, "d")
	}
	if cases[3].manifest != "n" {
		t.Errorf("HeartbeatRsp manifest = %q, want %q", cases[3].manifest, "n")
	}
}

// ---------------------------------------------------------------------------
// HandshakeReq (manifest "d")
// ---------------------------------------------------------------------------

// TestHandshakeReq_ScalaDecode loads the Scala-generated HandshakeReq fixture
// and verifies Go proto.Unmarshal recovers the expected fields.
//
// Fixture values:
//
//	from = UniqueAddress(pekko://BinaryGen@127.0.0.1:25520, uid=12345)
//	to   = Address(pekko, GoSystem, 127.0.0.1, 25521)
func TestHandshakeReq_ScalaDecode(t *testing.T) {
	data := loadFixtureArtery(t, "artery_handshake_req.bin")
	req := &gproto.HandshakeReq{}
	if err := proto.Unmarshal(data, req); err != nil {
		t.Fatalf("proto.Unmarshal HandshakeReq: %v", err)
	}

	// Verify "from" UniqueAddress
	from := req.GetFrom()
	if from == nil {
		t.Fatal("HandshakeReq.From is nil")
	}
	if from.GetUid() != 12345 {
		t.Errorf("From.Uid = %d, want 12345", from.GetUid())
	}
	fromAddr := from.GetAddress()
	if fromAddr == nil {
		t.Fatal("HandshakeReq.From.Address is nil")
	}
	if fromAddr.GetSystem() != "BinaryGen" {
		t.Errorf("From.System = %q, want %q", fromAddr.GetSystem(), "BinaryGen")
	}
	if fromAddr.GetHostname() != "127.0.0.1" {
		t.Errorf("From.Hostname = %q, want %q", fromAddr.GetHostname(), "127.0.0.1")
	}
	if fromAddr.GetPort() != 25520 {
		t.Errorf("From.Port = %d, want 25520", fromAddr.GetPort())
	}
	if fromAddr.GetProtocol() != "pekko" {
		t.Errorf("From.Protocol = %q, want %q", fromAddr.GetProtocol(), "pekko")
	}

	// Verify "to" Address
	to := req.GetTo()
	if to == nil {
		t.Fatal("HandshakeReq.To is nil")
	}
	if to.GetSystem() != "GoSystem" {
		t.Errorf("To.System = %q, want %q", to.GetSystem(), "GoSystem")
	}
	if to.GetHostname() != "127.0.0.1" {
		t.Errorf("To.Hostname = %q, want %q", to.GetHostname(), "127.0.0.1")
	}
	if to.GetPort() != 25521 {
		t.Errorf("To.Port = %d, want 25521", to.GetPort())
	}
	if to.GetProtocol() != "pekko" {
		t.Errorf("To.Protocol = %q, want %q", to.GetProtocol(), "pekko")
	}
}

// TestHandshakeReq_GoMatchesScala encodes the same HandshakeReq values in Go
// and verifies byte-identical output to the Scala fixture.
func TestHandshakeReq_GoMatchesScala(t *testing.T) {
	scala := loadFixtureArtery(t, "artery_handshake_req.bin")

	uid := uint64(12345)
	from := &gproto.UniqueAddress{
		Address: &gproto.Address{
			Protocol: proto.String("pekko"),
			System:   proto.String("BinaryGen"),
			Hostname: proto.String("127.0.0.1"),
			Port:     proto.Uint32(25520),
		},
		Uid: proto.Uint64(uid),
	}
	to := &gproto.Address{
		Protocol: proto.String("pekko"),
		System:   proto.String("GoSystem"),
		Hostname: proto.String("127.0.0.1"),
		Port:     proto.Uint32(25521),
	}
	req := &gproto.HandshakeReq{From: from, To: to}

	got, err := proto.Marshal(req)
	if err != nil {
		t.Fatalf("proto.Marshal: %v", err)
	}
	if !bytes.Equal(got, scala) {
		t.Errorf("Go bytes (%d):\n  %x\nScala (%d):\n  %x", len(got), got, len(scala), scala)
	}
}

// TestHandshakeReq_AddressFieldOrder verifies the Artery Address uses
// protocol=1, system=2, hostname=3, port=4 field ordering (not DData ordering).
//
// Expected prefix for "pekko" protocol field: tag 0x0a (field 1, len-delim).
func TestHandshakeReq_AddressFieldOrder(t *testing.T) {
	scala := loadFixtureArtery(t, "artery_handshake_req.bin")
	// The first address bytes embedded in from.UniqueAddress.Address should start
	// with: 0a 05 "pekko" (field 1 = protocol)
	wantProtocolTag := []byte{0x0a, 0x05, 'p', 'e', 'k', 'k', 'o'}
	if !bytes.Contains(scala, wantProtocolTag) {
		t.Errorf("protocol field (0x0a) not found at expected position in %x", scala)
	}
}

// TestHandshakeReq_RoundTrip encodes a HandshakeReq in Go, decodes it back,
// and verifies all fields are preserved.
func TestHandshakeReq_RoundTrip(t *testing.T) {
	req := &gproto.HandshakeReq{
		From: &gproto.UniqueAddress{
			Address: &gproto.Address{
				Protocol: proto.String("pekko"),
				System:   proto.String("TestSystem"),
				Hostname: proto.String("10.0.0.1"),
				Port:     proto.Uint32(2552),
			},
			Uid: proto.Uint64(99999),
		},
		To: &gproto.Address{
			Protocol: proto.String("pekko"),
			System:   proto.String("OtherSystem"),
			Hostname: proto.String("10.0.0.2"),
			Port:     proto.Uint32(2552),
		},
	}
	b, err := proto.Marshal(req)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	got := &gproto.HandshakeReq{}
	if err := proto.Unmarshal(b, got); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	if got.GetFrom().GetUid() != 99999 {
		t.Errorf("From.Uid = %d, want 99999", got.GetFrom().GetUid())
	}
	if got.GetTo().GetSystem() != "OtherSystem" {
		t.Errorf("To.System = %q, want %q", got.GetTo().GetSystem(), "OtherSystem")
	}
}

// ---------------------------------------------------------------------------
// ArteryHeartbeat (manifest "m") — empty payload
// ---------------------------------------------------------------------------

// TestHeartbeat_IsEmpty verifies the Heartbeat fixture is 0 bytes.
func TestHeartbeat_IsEmpty(t *testing.T) {
	data := loadFixtureArtery(t, "artery_heartbeat.bin")
	if len(data) != 0 {
		t.Errorf("ArteryHeartbeat fixture has %d bytes, want 0; data: %x", len(data), data)
	}
}

// TestHeartbeat_GoProducesEmpty verifies Go also produces empty bytes for Heartbeat.
// ArteryHeartbeat is a Scala singleton serialized to empty bytes.
func TestHeartbeat_GoProducesEmpty(t *testing.T) {
	// In Go, Heartbeat is represented as nil/empty payload — nothing to marshal.
	// Verify the fixture confirms this expectation.
	scala := loadFixtureArtery(t, "artery_heartbeat.bin")
	if !bytes.Equal(scala, []byte{}) {
		t.Errorf("expected empty, got %x", scala)
	}
}

// ---------------------------------------------------------------------------
// ArteryHeartbeatRsp (manifest "n")
// ---------------------------------------------------------------------------

// TestHeartbeatRsp_ScalaDecode decodes the Scala HeartbeatRsp fixture and
// verifies the uid field (fixture uses uid=99).
func TestHeartbeatRsp_ScalaDecode(t *testing.T) {
	data := loadFixtureArtery(t, "artery_heartbeat_rsp.bin")
	rsp := &gproto.ArteryHeartbeatRsp{}
	if err := proto.Unmarshal(data, rsp); err != nil {
		t.Fatalf("proto.Unmarshal HeartbeatRsp: %v", err)
	}
	if rsp.GetUid() != 99 {
		t.Errorf("Uid = %d, want 99", rsp.GetUid())
	}
}

// TestHeartbeatRsp_GoMatchesScala encodes ArteryHeartbeatRsp in Go and verifies
// byte-identical output to the Scala fixture.
// uid=99 → 0x08 0x63 (field 1, varint 99)
func TestHeartbeatRsp_GoMatchesScala(t *testing.T) {
	scala := loadFixtureArtery(t, "artery_heartbeat_rsp.bin")
	rsp := &gproto.ArteryHeartbeatRsp{Uid: proto.Uint64(99)}
	got, err := proto.Marshal(rsp)
	if err != nil {
		t.Fatalf("proto.Marshal: %v", err)
	}
	if !bytes.Equal(got, scala) {
		t.Errorf("Go bytes = %x, Scala = %x", got, scala)
	}
}

// TestHeartbeatRsp_ExpectedBytes verifies the exact wire bytes for uid=99:
// 0x08 (field 1, varint) + 0x63 (99).
func TestHeartbeatRsp_ExpectedBytes(t *testing.T) {
	data := loadFixtureArtery(t, "artery_heartbeat_rsp.bin")
	want := []byte{0x08, 0x63}
	if !bytes.Equal(data, want) {
		t.Errorf("HeartbeatRsp bytes = %x, want %x", data, want)
	}
}

func TestHeartbeatRsp_RoundTrip(t *testing.T) {
	rsp := &gproto.ArteryHeartbeatRsp{Uid: proto.Uint64(123456789)}
	b, err := proto.Marshal(rsp)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	got := &gproto.ArteryHeartbeatRsp{}
	if err := proto.Unmarshal(b, got); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	if got.GetUid() != 123456789 {
		t.Errorf("Uid = %d, want 123456789", got.GetUid())
	}
}

// ---------------------------------------------------------------------------
// HandshakeRsp (manifest "e") — MessageWithAddress{UniqueAddress}
// ---------------------------------------------------------------------------

// TestHandshakeRsp_ScalaDecode decodes the Scala HandshakeRsp fixture and
// verifies the embedded UniqueAddress (same as the "from" in HandshakeReq).
func TestHandshakeRsp_ScalaDecode(t *testing.T) {
	data := loadFixtureArtery(t, "artery_handshake_rsp.bin")
	rsp := &gproto.MessageWithAddress{}
	if err := proto.Unmarshal(data, rsp); err != nil {
		t.Fatalf("proto.Unmarshal HandshakeRsp: %v", err)
	}
	addr := rsp.GetAddress()
	if addr == nil {
		t.Fatal("HandshakeRsp.Address is nil")
	}
	if addr.GetUid() != 12345 {
		t.Errorf("Uid = %d, want 12345", addr.GetUid())
	}
	if addr.GetAddress().GetSystem() != "BinaryGen" {
		t.Errorf("System = %q, want %q", addr.GetAddress().GetSystem(), "BinaryGen")
	}
	if addr.GetAddress().GetPort() != 25520 {
		t.Errorf("Port = %d, want 25520", addr.GetAddress().GetPort())
	}
}

// TestHandshakeRsp_GoMatchesScala verifies Go proto.Marshal produces the same bytes.
func TestHandshakeRsp_GoMatchesScala(t *testing.T) {
	scala := loadFixtureArtery(t, "artery_handshake_rsp.bin")
	rsp := &gproto.MessageWithAddress{
		Address: &gproto.UniqueAddress{
			Address: &gproto.Address{
				Protocol: proto.String("pekko"),
				System:   proto.String("BinaryGen"),
				Hostname: proto.String("127.0.0.1"),
				Port:     proto.Uint32(25520),
			},
			Uid: proto.Uint64(12345),
		},
	}
	got, err := proto.Marshal(rsp)
	if err != nil {
		t.Fatalf("proto.Marshal: %v", err)
	}
	if !bytes.Equal(got, scala) {
		t.Errorf("Go bytes (%d):\n  %x\nScala (%d):\n  %x", len(got), got, len(scala), scala)
	}
}

// ---------------------------------------------------------------------------
// Wire format structure tests
// ---------------------------------------------------------------------------

// TestHandshakeReq_Size verifies the expected byte count for the fixture values.
// Computed from proto field layout:
//
//	from UniqueAddress (38 bytes) → total outer field: 40 bytes
//	to   Address (32 bytes)      → total outer field: 34 bytes
//	Total: 74 bytes
func TestHandshakeReq_Size(t *testing.T) {
	data := loadFixtureArtery(t, "artery_handshake_req.bin")
	if len(data) != 74 {
		t.Errorf("HandshakeReq fixture size = %d, want 74", len(data))
	}
}

// TestHeartbeatRsp_Size verifies the expected byte count for uid=99 (1-byte varint).
func TestHeartbeatRsp_Size(t *testing.T) {
	data := loadFixtureArtery(t, "artery_heartbeat_rsp.bin")
	if len(data) != 2 {
		t.Errorf("HeartbeatRsp fixture size = %d, want 2", len(data))
	}
}
