//
// Licensed to the Apache Software Foundation (ASF) under one or more
// license agreements; and to You under the Apache License, version 2.0:
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// This file is part of the Apache Pekko project, which was derived from Akka.

//
// Copyright (C) 2009-2022 Lightbend Inc. <https://www.lightbend.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: WireFormats.proto

package remote

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Defines the type of the PekkoControlMessage command type
type CommandType int32

const (
	CommandType_ASSOCIATE                  CommandType = 1
	CommandType_DISASSOCIATE               CommandType = 2
	CommandType_HEARTBEAT                  CommandType = 3
	CommandType_DISASSOCIATE_SHUTTING_DOWN CommandType = 4 // Remote system is going down and will not accepts new connections
	CommandType_DISASSOCIATE_QUARANTINED   CommandType = 5 // Remote system refused the association since the current system is quarantined
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		1: "ASSOCIATE",
		2: "DISASSOCIATE",
		3: "HEARTBEAT",
		4: "DISASSOCIATE_SHUTTING_DOWN",
		5: "DISASSOCIATE_QUARANTINED",
	}
	CommandType_value = map[string]int32{
		"ASSOCIATE":                  1,
		"DISASSOCIATE":               2,
		"HEARTBEAT":                  3,
		"DISASSOCIATE_SHUTTING_DOWN": 4,
		"DISASSOCIATE_QUARANTINED":   5,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_WireFormats_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_WireFormats_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CommandType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CommandType(num)
	return nil
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{0}
}

// *
// java.util.concurrent.TimeUnit enum
type TimeUnit int32

const (
	TimeUnit_NANOSECONDS  TimeUnit = 1
	TimeUnit_MICROSECONDS TimeUnit = 2
	TimeUnit_MILLISECONDS TimeUnit = 3
	TimeUnit_SECONDS      TimeUnit = 4
	TimeUnit_MINUTES      TimeUnit = 5
	TimeUnit_HOURS        TimeUnit = 6
	TimeUnit_DAYS         TimeUnit = 7
)

// Enum value maps for TimeUnit.
var (
	TimeUnit_name = map[int32]string{
		1: "NANOSECONDS",
		2: "MICROSECONDS",
		3: "MILLISECONDS",
		4: "SECONDS",
		5: "MINUTES",
		6: "HOURS",
		7: "DAYS",
	}
	TimeUnit_value = map[string]int32{
		"NANOSECONDS":  1,
		"MICROSECONDS": 2,
		"MILLISECONDS": 3,
		"SECONDS":      4,
		"MINUTES":      5,
		"HOURS":        6,
		"DAYS":         7,
	}
)

func (x TimeUnit) Enum() *TimeUnit {
	p := new(TimeUnit)
	*p = x
	return p
}

func (x TimeUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_WireFormats_proto_enumTypes[1].Descriptor()
}

func (TimeUnit) Type() protoreflect.EnumType {
	return &file_WireFormats_proto_enumTypes[1]
}

func (x TimeUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TimeUnit) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TimeUnit(num)
	return nil
}

// Deprecated: Use TimeUnit.Descriptor instead.
func (TimeUnit) EnumDescriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{1}
}

type AckAndEnvelopeContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *AcknowledgementInfo   `protobuf:"bytes,1,opt,name=ack" json:"ack,omitempty"`
	Envelope      *RemoteEnvelope        `protobuf:"bytes,2,opt,name=envelope" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckAndEnvelopeContainer) Reset() {
	*x = AckAndEnvelopeContainer{}
	mi := &file_WireFormats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAndEnvelopeContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAndEnvelopeContainer) ProtoMessage() {}

func (x *AckAndEnvelopeContainer) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAndEnvelopeContainer.ProtoReflect.Descriptor instead.
func (*AckAndEnvelopeContainer) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{0}
}

func (x *AckAndEnvelopeContainer) GetAck() *AcknowledgementInfo {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *AckAndEnvelopeContainer) GetEnvelope() *RemoteEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// *
// Defines a remote message.
type RemoteEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     *ActorRefData          `protobuf:"bytes,1,req,name=recipient" json:"recipient,omitempty"`
	Message       *SerializedMessage     `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Sender        *ActorRefData          `protobuf:"bytes,4,opt,name=sender" json:"sender,omitempty"`
	Seq           *uint64                `protobuf:"fixed64,5,opt,name=seq" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteEnvelope) Reset() {
	*x = RemoteEnvelope{}
	mi := &file_WireFormats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEnvelope) ProtoMessage() {}

func (x *RemoteEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEnvelope.ProtoReflect.Descriptor instead.
func (*RemoteEnvelope) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteEnvelope) GetRecipient() *ActorRefData {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *RemoteEnvelope) GetMessage() *SerializedMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RemoteEnvelope) GetSender() *ActorRefData {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *RemoteEnvelope) GetSeq() uint64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

type AcknowledgementInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CumulativeAck *uint64                `protobuf:"fixed64,1,req,name=cumulativeAck" json:"cumulativeAck,omitempty"`
	Nacks         []uint64               `protobuf:"fixed64,2,rep,name=nacks" json:"nacks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgementInfo) Reset() {
	*x = AcknowledgementInfo{}
	mi := &file_WireFormats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgementInfo) ProtoMessage() {}

func (x *AcknowledgementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgementInfo.ProtoReflect.Descriptor instead.
func (*AcknowledgementInfo) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{2}
}

func (x *AcknowledgementInfo) GetCumulativeAck() uint64 {
	if x != nil && x.CumulativeAck != nil {
		return *x.CumulativeAck
	}
	return 0
}

func (x *AcknowledgementInfo) GetNacks() []uint64 {
	if x != nil {
		return x.Nacks
	}
	return nil
}

// *
// Defines a remote ActorRef that "remembers" and uses its original Actor instance
// on the original node.
type ActorRefData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorRefData) Reset() {
	*x = ActorRefData{}
	mi := &file_WireFormats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorRefData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRefData) ProtoMessage() {}

func (x *ActorRefData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRefData.ProtoReflect.Descriptor instead.
func (*ActorRefData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{3}
}

func (x *ActorRefData) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

// *
// Defines a message.
type SerializedMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         []byte                 `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	SerializerId    *int32                 `protobuf:"varint,2,req,name=serializerId" json:"serializerId,omitempty"`
	MessageManifest []byte                 `protobuf:"bytes,3,opt,name=messageManifest" json:"messageManifest,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SerializedMessage) Reset() {
	*x = SerializedMessage{}
	mi := &file_WireFormats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedMessage) ProtoMessage() {}

func (x *SerializedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedMessage.ProtoReflect.Descriptor instead.
func (*SerializedMessage) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{4}
}

func (x *SerializedMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SerializedMessage) GetSerializerId() int32 {
	if x != nil && x.SerializerId != nil {
		return *x.SerializerId
	}
	return 0
}

func (x *SerializedMessage) GetMessageManifest() []byte {
	if x != nil {
		return x.MessageManifest
	}
	return nil
}

// *
// Defines org.apache.pekko.remote.DaemonMsgCreate
type DaemonMsgCreateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Props         *PropsData             `protobuf:"bytes,1,req,name=props" json:"props,omitempty"`
	Deploy        *DeployData            `protobuf:"bytes,2,req,name=deploy" json:"deploy,omitempty"`
	Path          *string                `protobuf:"bytes,3,req,name=path" json:"path,omitempty"`
	Supervisor    *ActorRefData          `protobuf:"bytes,4,req,name=supervisor" json:"supervisor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonMsgCreateData) Reset() {
	*x = DaemonMsgCreateData{}
	mi := &file_WireFormats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonMsgCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonMsgCreateData) ProtoMessage() {}

func (x *DaemonMsgCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonMsgCreateData.ProtoReflect.Descriptor instead.
func (*DaemonMsgCreateData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{5}
}

func (x *DaemonMsgCreateData) GetProps() *PropsData {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *DaemonMsgCreateData) GetDeploy() *DeployData {
	if x != nil {
		return x.Deploy
	}
	return nil
}

func (x *DaemonMsgCreateData) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *DaemonMsgCreateData) GetSupervisor() *ActorRefData {
	if x != nil {
		return x.Supervisor
	}
	return nil
}

// *
// Serialization of org.apache.pekko.actor.Props
type PropsData struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Deploy *DeployData            `protobuf:"bytes,2,req,name=deploy" json:"deploy,omitempty"`
	Clazz  *string                `protobuf:"bytes,3,req,name=clazz" json:"clazz,omitempty"`
	Args   [][]byte               `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	// serialized props parameters
	// older wire protocol: contains class name for each arg
	// newer wire protocol: contains string manifest for each arg
	Manifests []string `protobuf:"bytes,5,rep,name=manifests" json:"manifests,omitempty"`
	// newer wire protocol: serializer id for each arg
	SerializerIds []int32 `protobuf:"varint,6,rep,name=serializerIds" json:"serializerIds,omitempty"`
	// additionally a flag per position to indicate if it was
	// serialized with manifest or not
	HasManifest   []bool `protobuf:"varint,7,rep,name=hasManifest" json:"hasManifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropsData) Reset() {
	*x = PropsData{}
	mi := &file_WireFormats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropsData) ProtoMessage() {}

func (x *PropsData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropsData.ProtoReflect.Descriptor instead.
func (*PropsData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{6}
}

func (x *PropsData) GetDeploy() *DeployData {
	if x != nil {
		return x.Deploy
	}
	return nil
}

func (x *PropsData) GetClazz() string {
	if x != nil && x.Clazz != nil {
		return *x.Clazz
	}
	return ""
}

func (x *PropsData) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PropsData) GetManifests() []string {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (x *PropsData) GetSerializerIds() []int32 {
	if x != nil {
		return x.SerializerIds
	}
	return nil
}

func (x *PropsData) GetHasManifest() []bool {
	if x != nil {
		return x.HasManifest
	}
	return nil
}

// *
// Serialization of org.apache.pekko.actor.Deploy
type DeployData struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Path         *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Config       []byte                 `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
	RouterConfig []byte                 `protobuf:"bytes,3,opt,name=routerConfig" json:"routerConfig,omitempty"`
	Scope        []byte                 `protobuf:"bytes,4,opt,name=scope" json:"scope,omitempty"`
	Dispatcher   *string                `protobuf:"bytes,5,opt,name=dispatcher" json:"dispatcher,omitempty"`
	// older wire protocol: hardcoded class used to look up serializer
	// newer wire protocol: serializer id and manifest available for each
	ScopeSerializerId        *int32   `protobuf:"varint,6,opt,name=scopeSerializerId" json:"scopeSerializerId,omitempty"`
	ScopeManifest            *string  `protobuf:"bytes,7,opt,name=scopeManifest" json:"scopeManifest,omitempty"`
	ConfigSerializerId       *int32   `protobuf:"varint,8,opt,name=configSerializerId" json:"configSerializerId,omitempty"`
	ConfigManifest           *string  `protobuf:"bytes,9,opt,name=configManifest" json:"configManifest,omitempty"`
	RouterConfigSerializerId *int32   `protobuf:"varint,10,opt,name=routerConfigSerializerId" json:"routerConfigSerializerId,omitempty"`
	RouterConfigManifest     *string  `protobuf:"bytes,11,opt,name=routerConfigManifest" json:"routerConfigManifest,omitempty"`
	Tags                     []string `protobuf:"bytes,12,rep,name=tags" json:"tags,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeployData) Reset() {
	*x = DeployData{}
	mi := &file_WireFormats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployData) ProtoMessage() {}

func (x *DeployData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployData.ProtoReflect.Descriptor instead.
func (*DeployData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{7}
}

func (x *DeployData) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *DeployData) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DeployData) GetRouterConfig() []byte {
	if x != nil {
		return x.RouterConfig
	}
	return nil
}

func (x *DeployData) GetScope() []byte {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *DeployData) GetDispatcher() string {
	if x != nil && x.Dispatcher != nil {
		return *x.Dispatcher
	}
	return ""
}

func (x *DeployData) GetScopeSerializerId() int32 {
	if x != nil && x.ScopeSerializerId != nil {
		return *x.ScopeSerializerId
	}
	return 0
}

func (x *DeployData) GetScopeManifest() string {
	if x != nil && x.ScopeManifest != nil {
		return *x.ScopeManifest
	}
	return ""
}

func (x *DeployData) GetConfigSerializerId() int32 {
	if x != nil && x.ConfigSerializerId != nil {
		return *x.ConfigSerializerId
	}
	return 0
}

func (x *DeployData) GetConfigManifest() string {
	if x != nil && x.ConfigManifest != nil {
		return *x.ConfigManifest
	}
	return ""
}

func (x *DeployData) GetRouterConfigSerializerId() int32 {
	if x != nil && x.RouterConfigSerializerId != nil {
		return *x.RouterConfigSerializerId
	}
	return 0
}

func (x *DeployData) GetRouterConfigManifest() string {
	if x != nil && x.RouterConfigManifest != nil {
		return *x.RouterConfigManifest
	}
	return ""
}

func (x *DeployData) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// *
// Message format of Pekko Protocol.
// Message contains either a payload or an instruction.
type PekkoProtocolMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Instruction   *PekkoControlMessage   `protobuf:"bytes,2,opt,name=instruction" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PekkoProtocolMessage) Reset() {
	*x = PekkoProtocolMessage{}
	mi := &file_WireFormats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PekkoProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PekkoProtocolMessage) ProtoMessage() {}

func (x *PekkoProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PekkoProtocolMessage.ProtoReflect.Descriptor instead.
func (*PekkoProtocolMessage) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{8}
}

func (x *PekkoProtocolMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PekkoProtocolMessage) GetInstruction() *PekkoControlMessage {
	if x != nil {
		return x.Instruction
	}
	return nil
}

// *
// Defines some control messages for the remoting
type PekkoControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandType   *CommandType           `protobuf:"varint,1,req,name=commandType,enum=CommandType" json:"commandType,omitempty"`
	HandshakeInfo *PekkoHandshakeInfo    `protobuf:"bytes,2,opt,name=handshakeInfo" json:"handshakeInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PekkoControlMessage) Reset() {
	*x = PekkoControlMessage{}
	mi := &file_WireFormats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PekkoControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PekkoControlMessage) ProtoMessage() {}

func (x *PekkoControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PekkoControlMessage.ProtoReflect.Descriptor instead.
func (*PekkoControlMessage) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{9}
}

func (x *PekkoControlMessage) GetCommandType() CommandType {
	if x != nil && x.CommandType != nil {
		return *x.CommandType
	}
	return CommandType_ASSOCIATE
}

func (x *PekkoControlMessage) GetHandshakeInfo() *PekkoHandshakeInfo {
	if x != nil {
		return x.HandshakeInfo
	}
	return nil
}

type PekkoHandshakeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        *AddressData           `protobuf:"bytes,1,req,name=origin" json:"origin,omitempty"`
	Uid           *uint64                `protobuf:"fixed64,2,req,name=uid" json:"uid,omitempty"`
	Cookie        *string                `protobuf:"bytes,3,opt,name=cookie" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PekkoHandshakeInfo) Reset() {
	*x = PekkoHandshakeInfo{}
	mi := &file_WireFormats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PekkoHandshakeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PekkoHandshakeInfo) ProtoMessage() {}

func (x *PekkoHandshakeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PekkoHandshakeInfo.ProtoReflect.Descriptor instead.
func (*PekkoHandshakeInfo) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{10}
}

func (x *PekkoHandshakeInfo) GetOrigin() *AddressData {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *PekkoHandshakeInfo) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *PekkoHandshakeInfo) GetCookie() string {
	if x != nil && x.Cookie != nil {
		return *x.Cookie
	}
	return ""
}

type FiniteDuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int64                 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	Unit          *TimeUnit              `protobuf:"varint,2,req,name=unit,enum=TimeUnit" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiniteDuration) Reset() {
	*x = FiniteDuration{}
	mi := &file_WireFormats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiniteDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiniteDuration) ProtoMessage() {}

func (x *FiniteDuration) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiniteDuration.ProtoReflect.Descriptor instead.
func (*FiniteDuration) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{11}
}

func (x *FiniteDuration) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *FiniteDuration) GetUnit() TimeUnit {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return TimeUnit_NANOSECONDS
}

type RemoteScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *AddressData           `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteScope) Reset() {
	*x = RemoteScope{}
	mi := &file_WireFormats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteScope) ProtoMessage() {}

func (x *RemoteScope) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteScope.ProtoReflect.Descriptor instead.
func (*RemoteScope) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{12}
}

func (x *RemoteScope) GetNode() *AddressData {
	if x != nil {
		return x.Node
	}
	return nil
}

type DefaultResizer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LowerBound        *uint32                `protobuf:"varint,1,req,name=lowerBound" json:"lowerBound,omitempty"`
	UpperBound        *uint32                `protobuf:"varint,2,req,name=upperBound" json:"upperBound,omitempty"`
	PressureThreshold *uint32                `protobuf:"varint,3,req,name=pressureThreshold" json:"pressureThreshold,omitempty"`
	RampupRate        *float64               `protobuf:"fixed64,4,req,name=rampupRate" json:"rampupRate,omitempty"`
	BackoffThreshold  *float64               `protobuf:"fixed64,5,req,name=backoffThreshold" json:"backoffThreshold,omitempty"`
	BackoffRate       *float64               `protobuf:"fixed64,6,req,name=backoffRate" json:"backoffRate,omitempty"`
	MessagesPerResize *uint32                `protobuf:"varint,7,req,name=messagesPerResize" json:"messagesPerResize,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DefaultResizer) Reset() {
	*x = DefaultResizer{}
	mi := &file_WireFormats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultResizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResizer) ProtoMessage() {}

func (x *DefaultResizer) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResizer.ProtoReflect.Descriptor instead.
func (*DefaultResizer) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{13}
}

func (x *DefaultResizer) GetLowerBound() uint32 {
	if x != nil && x.LowerBound != nil {
		return *x.LowerBound
	}
	return 0
}

func (x *DefaultResizer) GetUpperBound() uint32 {
	if x != nil && x.UpperBound != nil {
		return *x.UpperBound
	}
	return 0
}

func (x *DefaultResizer) GetPressureThreshold() uint32 {
	if x != nil && x.PressureThreshold != nil {
		return *x.PressureThreshold
	}
	return 0
}

func (x *DefaultResizer) GetRampupRate() float64 {
	if x != nil && x.RampupRate != nil {
		return *x.RampupRate
	}
	return 0
}

func (x *DefaultResizer) GetBackoffThreshold() float64 {
	if x != nil && x.BackoffThreshold != nil {
		return *x.BackoffThreshold
	}
	return 0
}

func (x *DefaultResizer) GetBackoffRate() float64 {
	if x != nil && x.BackoffRate != nil {
		return *x.BackoffRate
	}
	return 0
}

func (x *DefaultResizer) GetMessagesPerResize() uint32 {
	if x != nil && x.MessagesPerResize != nil {
		return *x.MessagesPerResize
	}
	return 0
}

type FromConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Resizer          *Payload               `protobuf:"bytes,1,opt,name=resizer" json:"resizer,omitempty"`
	RouterDispatcher *string                `protobuf:"bytes,2,opt,name=routerDispatcher" json:"routerDispatcher,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FromConfig) Reset() {
	*x = FromConfig{}
	mi := &file_WireFormats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromConfig) ProtoMessage() {}

func (x *FromConfig) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromConfig.ProtoReflect.Descriptor instead.
func (*FromConfig) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{14}
}

func (x *FromConfig) GetResizer() *Payload {
	if x != nil {
		return x.Resizer
	}
	return nil
}

func (x *FromConfig) GetRouterDispatcher() string {
	if x != nil && x.RouterDispatcher != nil {
		return *x.RouterDispatcher
	}
	return ""
}

type GenericRoutingPool struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NrOfInstances     *uint32                `protobuf:"varint,1,req,name=nrOfInstances" json:"nrOfInstances,omitempty"`
	RouterDispatcher  *string                `protobuf:"bytes,2,opt,name=routerDispatcher" json:"routerDispatcher,omitempty"`
	UsePoolDispatcher *bool                  `protobuf:"varint,3,req,name=usePoolDispatcher" json:"usePoolDispatcher,omitempty"`
	Resizer           *Payload               `protobuf:"bytes,4,opt,name=resizer" json:"resizer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenericRoutingPool) Reset() {
	*x = GenericRoutingPool{}
	mi := &file_WireFormats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericRoutingPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRoutingPool) ProtoMessage() {}

func (x *GenericRoutingPool) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRoutingPool.ProtoReflect.Descriptor instead.
func (*GenericRoutingPool) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{15}
}

func (x *GenericRoutingPool) GetNrOfInstances() uint32 {
	if x != nil && x.NrOfInstances != nil {
		return *x.NrOfInstances
	}
	return 0
}

func (x *GenericRoutingPool) GetRouterDispatcher() string {
	if x != nil && x.RouterDispatcher != nil {
		return *x.RouterDispatcher
	}
	return ""
}

func (x *GenericRoutingPool) GetUsePoolDispatcher() bool {
	if x != nil && x.UsePoolDispatcher != nil {
		return *x.UsePoolDispatcher
	}
	return false
}

func (x *GenericRoutingPool) GetResizer() *Payload {
	if x != nil {
		return x.Resizer
	}
	return nil
}

type ScatterGatherPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generic       *GenericRoutingPool    `protobuf:"bytes,1,req,name=generic" json:"generic,omitempty"`
	Within        *FiniteDuration        `protobuf:"bytes,2,req,name=within" json:"within,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScatterGatherPool) Reset() {
	*x = ScatterGatherPool{}
	mi := &file_WireFormats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScatterGatherPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScatterGatherPool) ProtoMessage() {}

func (x *ScatterGatherPool) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScatterGatherPool.ProtoReflect.Descriptor instead.
func (*ScatterGatherPool) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{16}
}

func (x *ScatterGatherPool) GetGeneric() *GenericRoutingPool {
	if x != nil {
		return x.Generic
	}
	return nil
}

func (x *ScatterGatherPool) GetWithin() *FiniteDuration {
	if x != nil {
		return x.Within
	}
	return nil
}

type TailChoppingPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generic       *GenericRoutingPool    `protobuf:"bytes,1,req,name=generic" json:"generic,omitempty"`
	Within        *FiniteDuration        `protobuf:"bytes,2,req,name=within" json:"within,omitempty"`
	Interval      *FiniteDuration        `protobuf:"bytes,3,req,name=interval" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailChoppingPool) Reset() {
	*x = TailChoppingPool{}
	mi := &file_WireFormats_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailChoppingPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailChoppingPool) ProtoMessage() {}

func (x *TailChoppingPool) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailChoppingPool.ProtoReflect.Descriptor instead.
func (*TailChoppingPool) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{17}
}

func (x *TailChoppingPool) GetGeneric() *GenericRoutingPool {
	if x != nil {
		return x.Generic
	}
	return nil
}

func (x *TailChoppingPool) GetWithin() *FiniteDuration {
	if x != nil {
		return x.Within
	}
	return nil
}

func (x *TailChoppingPool) GetInterval() *FiniteDuration {
	if x != nil {
		return x.Interval
	}
	return nil
}

// *
// Defines a remote address.
type AddressData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *string                `protobuf:"bytes,1,req,name=system" json:"system,omitempty"`
	Hostname      *string                `protobuf:"bytes,2,req,name=hostname" json:"hostname,omitempty"`
	Port          *uint32                `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	Protocol      *string                `protobuf:"bytes,4,opt,name=protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressData) Reset() {
	*x = AddressData{}
	mi := &file_WireFormats_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressData) ProtoMessage() {}

func (x *AddressData) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressData.ProtoReflect.Descriptor instead.
func (*AddressData) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{18}
}

func (x *AddressData) GetSystem() string {
	if x != nil && x.System != nil {
		return *x.System
	}
	return ""
}

func (x *AddressData) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *AddressData) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *AddressData) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

type RemoteRouterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Local         *Payload               `protobuf:"bytes,1,req,name=local" json:"local,omitempty"`
	Nodes         []*AddressData         `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteRouterConfig) Reset() {
	*x = RemoteRouterConfig{}
	mi := &file_WireFormats_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteRouterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteRouterConfig) ProtoMessage() {}

func (x *RemoteRouterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_WireFormats_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteRouterConfig.ProtoReflect.Descriptor instead.
func (*RemoteRouterConfig) Descriptor() ([]byte, []int) {
	return file_WireFormats_proto_rawDescGZIP(), []int{19}
}

func (x *RemoteRouterConfig) GetLocal() *Payload {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *RemoteRouterConfig) GetNodes() []*AddressData {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_WireFormats_proto protoreflect.FileDescriptor

const file_WireFormats_proto_rawDesc = "" +
	"\n" +
	"\x11WireFormats.proto\x1a\x16ContainerFormats.proto\"n\n" +
	"\x17AckAndEnvelopeContainer\x12&\n" +
	"\x03ack\x18\x01 \x01(\v2\x14.AcknowledgementInfoR\x03ack\x12+\n" +
	"\benvelope\x18\x02 \x01(\v2\x0f.RemoteEnvelopeR\benvelope\"\xa4\x01\n" +
	"\x0eRemoteEnvelope\x12+\n" +
	"\trecipient\x18\x01 \x02(\v2\r.ActorRefDataR\trecipient\x12,\n" +
	"\amessage\x18\x02 \x02(\v2\x12.SerializedMessageR\amessage\x12%\n" +
	"\x06sender\x18\x04 \x01(\v2\r.ActorRefDataR\x06sender\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x06R\x03seq\"Q\n" +
	"\x13AcknowledgementInfo\x12$\n" +
	"\rcumulativeAck\x18\x01 \x02(\x06R\rcumulativeAck\x12\x14\n" +
	"\x05nacks\x18\x02 \x03(\x06R\x05nacks\"\"\n" +
	"\fActorRefData\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\"{\n" +
	"\x11SerializedMessage\x12\x18\n" +
	"\amessage\x18\x01 \x02(\fR\amessage\x12\"\n" +
	"\fserializerId\x18\x02 \x02(\x05R\fserializerId\x12(\n" +
	"\x0fmessageManifest\x18\x03 \x01(\fR\x0fmessageManifest\"\x9f\x01\n" +
	"\x13DaemonMsgCreateData\x12 \n" +
	"\x05props\x18\x01 \x02(\v2\n" +
	".PropsDataR\x05props\x12#\n" +
	"\x06deploy\x18\x02 \x02(\v2\v.DeployDataR\x06deploy\x12\x12\n" +
	"\x04path\x18\x03 \x02(\tR\x04path\x12-\n" +
	"\n" +
	"supervisor\x18\x04 \x02(\v2\r.ActorRefDataR\n" +
	"supervisor\"\xc0\x01\n" +
	"\tPropsData\x12#\n" +
	"\x06deploy\x18\x02 \x02(\v2\v.DeployDataR\x06deploy\x12\x14\n" +
	"\x05clazz\x18\x03 \x02(\tR\x05clazz\x12\x12\n" +
	"\x04args\x18\x04 \x03(\fR\x04args\x12\x1c\n" +
	"\tmanifests\x18\x05 \x03(\tR\tmanifests\x12$\n" +
	"\rserializerIds\x18\x06 \x03(\x05R\rserializerIds\x12 \n" +
	"\vhasManifest\x18\a \x03(\bR\vhasManifest\"\xc2\x03\n" +
	"\n" +
	"DeployData\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\x12\"\n" +
	"\frouterConfig\x18\x03 \x01(\fR\frouterConfig\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\fR\x05scope\x12\x1e\n" +
	"\n" +
	"dispatcher\x18\x05 \x01(\tR\n" +
	"dispatcher\x12,\n" +
	"\x11scopeSerializerId\x18\x06 \x01(\x05R\x11scopeSerializerId\x12$\n" +
	"\rscopeManifest\x18\a \x01(\tR\rscopeManifest\x12.\n" +
	"\x12configSerializerId\x18\b \x01(\x05R\x12configSerializerId\x12&\n" +
	"\x0econfigManifest\x18\t \x01(\tR\x0econfigManifest\x12:\n" +
	"\x18routerConfigSerializerId\x18\n" +
	" \x01(\x05R\x18routerConfigSerializerId\x122\n" +
	"\x14routerConfigManifest\x18\v \x01(\tR\x14routerConfigManifest\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\"h\n" +
	"\x14PekkoProtocolMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x126\n" +
	"\vinstruction\x18\x02 \x01(\v2\x14.PekkoControlMessageR\vinstruction\"\x80\x01\n" +
	"\x13PekkoControlMessage\x12.\n" +
	"\vcommandType\x18\x01 \x02(\x0e2\f.CommandTypeR\vcommandType\x129\n" +
	"\rhandshakeInfo\x18\x02 \x01(\v2\x13.PekkoHandshakeInfoR\rhandshakeInfo\"d\n" +
	"\x12PekkoHandshakeInfo\x12$\n" +
	"\x06origin\x18\x01 \x02(\v2\f.AddressDataR\x06origin\x12\x10\n" +
	"\x03uid\x18\x02 \x02(\x06R\x03uid\x12\x16\n" +
	"\x06cookie\x18\x03 \x01(\tR\x06cookie\"E\n" +
	"\x0eFiniteDuration\x12\x14\n" +
	"\x05value\x18\x01 \x02(\x03R\x05value\x12\x1d\n" +
	"\x04unit\x18\x02 \x02(\x0e2\t.TimeUnitR\x04unit\"/\n" +
	"\vRemoteScope\x12 \n" +
	"\x04node\x18\x01 \x02(\v2\f.AddressDataR\x04node\"\x9a\x02\n" +
	"\x0eDefaultResizer\x12\x1e\n" +
	"\n" +
	"lowerBound\x18\x01 \x02(\rR\n" +
	"lowerBound\x12\x1e\n" +
	"\n" +
	"upperBound\x18\x02 \x02(\rR\n" +
	"upperBound\x12,\n" +
	"\x11pressureThreshold\x18\x03 \x02(\rR\x11pressureThreshold\x12\x1e\n" +
	"\n" +
	"rampupRate\x18\x04 \x02(\x01R\n" +
	"rampupRate\x12*\n" +
	"\x10backoffThreshold\x18\x05 \x02(\x01R\x10backoffThreshold\x12 \n" +
	"\vbackoffRate\x18\x06 \x02(\x01R\vbackoffRate\x12,\n" +
	"\x11messagesPerResize\x18\a \x02(\rR\x11messagesPerResize\"\\\n" +
	"\n" +
	"FromConfig\x12\"\n" +
	"\aresizer\x18\x01 \x01(\v2\b.PayloadR\aresizer\x12*\n" +
	"\x10routerDispatcher\x18\x02 \x01(\tR\x10routerDispatcher\"\xb8\x01\n" +
	"\x12GenericRoutingPool\x12$\n" +
	"\rnrOfInstances\x18\x01 \x02(\rR\rnrOfInstances\x12*\n" +
	"\x10routerDispatcher\x18\x02 \x01(\tR\x10routerDispatcher\x12,\n" +
	"\x11usePoolDispatcher\x18\x03 \x02(\bR\x11usePoolDispatcher\x12\"\n" +
	"\aresizer\x18\x04 \x01(\v2\b.PayloadR\aresizer\"k\n" +
	"\x11ScatterGatherPool\x12-\n" +
	"\ageneric\x18\x01 \x02(\v2\x13.GenericRoutingPoolR\ageneric\x12'\n" +
	"\x06within\x18\x02 \x02(\v2\x0f.FiniteDurationR\x06within\"\x97\x01\n" +
	"\x10TailChoppingPool\x12-\n" +
	"\ageneric\x18\x01 \x02(\v2\x13.GenericRoutingPoolR\ageneric\x12'\n" +
	"\x06within\x18\x02 \x02(\v2\x0f.FiniteDurationR\x06within\x12+\n" +
	"\binterval\x18\x03 \x02(\v2\x0f.FiniteDurationR\binterval\"q\n" +
	"\vAddressData\x12\x16\n" +
	"\x06system\x18\x01 \x02(\tR\x06system\x12\x1a\n" +
	"\bhostname\x18\x02 \x02(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x02(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"X\n" +
	"\x12RemoteRouterConfig\x12\x1e\n" +
	"\x05local\x18\x01 \x02(\v2\b.PayloadR\x05local\x12\"\n" +
	"\x05nodes\x18\x02 \x03(\v2\f.AddressDataR\x05nodes*{\n" +
	"\vCommandType\x12\r\n" +
	"\tASSOCIATE\x10\x01\x12\x10\n" +
	"\fDISASSOCIATE\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\x12\x1e\n" +
	"\x1aDISASSOCIATE_SHUTTING_DOWN\x10\x04\x12\x1c\n" +
	"\x18DISASSOCIATE_QUARANTINED\x10\x05*n\n" +
	"\bTimeUnit\x12\x0f\n" +
	"\vNANOSECONDS\x10\x01\x12\x10\n" +
	"\fMICROSECONDS\x10\x02\x12\x10\n" +
	"\fMILLISECONDS\x10\x03\x12\v\n" +
	"\aSECONDS\x10\x04\x12\v\n" +
	"\aMINUTES\x10\x05\x12\t\n" +
	"\x05HOURS\x10\x06\x12\b\n" +
	"\x04DAYS\x10\aB\x1b\n" +
	"\x17org.apache.pekko.remoteH\x01"

var (
	file_WireFormats_proto_rawDescOnce sync.Once
	file_WireFormats_proto_rawDescData []byte
)

func file_WireFormats_proto_rawDescGZIP() []byte {
	file_WireFormats_proto_rawDescOnce.Do(func() {
		file_WireFormats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_WireFormats_proto_rawDesc), len(file_WireFormats_proto_rawDesc)))
	})
	return file_WireFormats_proto_rawDescData
}

var file_WireFormats_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_WireFormats_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_WireFormats_proto_goTypes = []any{
	(CommandType)(0),                // 0: CommandType
	(TimeUnit)(0),                   // 1: TimeUnit
	(*AckAndEnvelopeContainer)(nil), // 2: AckAndEnvelopeContainer
	(*RemoteEnvelope)(nil),          // 3: RemoteEnvelope
	(*AcknowledgementInfo)(nil),     // 4: AcknowledgementInfo
	(*ActorRefData)(nil),            // 5: ActorRefData
	(*SerializedMessage)(nil),       // 6: SerializedMessage
	(*DaemonMsgCreateData)(nil),     // 7: DaemonMsgCreateData
	(*PropsData)(nil),               // 8: PropsData
	(*DeployData)(nil),              // 9: DeployData
	(*PekkoProtocolMessage)(nil),    // 10: PekkoProtocolMessage
	(*PekkoControlMessage)(nil),     // 11: PekkoControlMessage
	(*PekkoHandshakeInfo)(nil),      // 12: PekkoHandshakeInfo
	(*FiniteDuration)(nil),          // 13: FiniteDuration
	(*RemoteScope)(nil),             // 14: RemoteScope
	(*DefaultResizer)(nil),          // 15: DefaultResizer
	(*FromConfig)(nil),              // 16: FromConfig
	(*GenericRoutingPool)(nil),      // 17: GenericRoutingPool
	(*ScatterGatherPool)(nil),       // 18: ScatterGatherPool
	(*TailChoppingPool)(nil),        // 19: TailChoppingPool
	(*AddressData)(nil),             // 20: AddressData
	(*RemoteRouterConfig)(nil),      // 21: RemoteRouterConfig
	(*Payload)(nil),                 // 22: Payload
}
var file_WireFormats_proto_depIdxs = []int32{
	4,  // 0: AckAndEnvelopeContainer.ack:type_name -> AcknowledgementInfo
	3,  // 1: AckAndEnvelopeContainer.envelope:type_name -> RemoteEnvelope
	5,  // 2: RemoteEnvelope.recipient:type_name -> ActorRefData
	6,  // 3: RemoteEnvelope.message:type_name -> SerializedMessage
	5,  // 4: RemoteEnvelope.sender:type_name -> ActorRefData
	8,  // 5: DaemonMsgCreateData.props:type_name -> PropsData
	9,  // 6: DaemonMsgCreateData.deploy:type_name -> DeployData
	5,  // 7: DaemonMsgCreateData.supervisor:type_name -> ActorRefData
	9,  // 8: PropsData.deploy:type_name -> DeployData
	11, // 9: PekkoProtocolMessage.instruction:type_name -> PekkoControlMessage
	0,  // 10: PekkoControlMessage.commandType:type_name -> CommandType
	12, // 11: PekkoControlMessage.handshakeInfo:type_name -> PekkoHandshakeInfo
	20, // 12: PekkoHandshakeInfo.origin:type_name -> AddressData
	1,  // 13: FiniteDuration.unit:type_name -> TimeUnit
	20, // 14: RemoteScope.node:type_name -> AddressData
	22, // 15: FromConfig.resizer:type_name -> Payload
	22, // 16: GenericRoutingPool.resizer:type_name -> Payload
	17, // 17: ScatterGatherPool.generic:type_name -> GenericRoutingPool
	13, // 18: ScatterGatherPool.within:type_name -> FiniteDuration
	17, // 19: TailChoppingPool.generic:type_name -> GenericRoutingPool
	13, // 20: TailChoppingPool.within:type_name -> FiniteDuration
	13, // 21: TailChoppingPool.interval:type_name -> FiniteDuration
	22, // 22: RemoteRouterConfig.local:type_name -> Payload
	20, // 23: RemoteRouterConfig.nodes:type_name -> AddressData
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_WireFormats_proto_init() }
func file_WireFormats_proto_init() {
	if File_WireFormats_proto != nil {
		return
	}
	file_ContainerFormats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_WireFormats_proto_rawDesc), len(file_WireFormats_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WireFormats_proto_goTypes,
		DependencyIndexes: file_WireFormats_proto_depIdxs,
		EnumInfos:         file_WireFormats_proto_enumTypes,
		MessageInfos:      file_WireFormats_proto_msgTypes,
	}.Build()
	File_WireFormats_proto = out.File
	file_WireFormats_proto_goTypes = nil
	file_WireFormats_proto_depIdxs = nil
}
